import { addDays, format } from "date-fns";
import type { CalendarEvent, Commission, CommissionInstallment, FinancialTransaction, MonthlyBudget, Task } from "@/types/database";

const today = format(new Date(), "yyyy-MM-dd");

export const demoEvents: CalendarEvent[] = [
  {
    id: "demo-event-1",
    user_id: "demo",
    title: "Reunião com proprietário",
    description: "Alinhar preço de entrada e exclusividade.",
    date: today,
    start_time: "09:00",
    end_time: "09:45",
    type: "reunião",
    location: "Escritório",
    status: "agendado",
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-event-2",
    user_id: "demo",
    title: "Visita no apartamento do Centro",
    description: "Cliente busca 2 quartos com vaga.",
    date: today,
    start_time: "11:00",
    end_time: "12:00",
    type: "visita",
    location: "Centro",
    status: "agendado",
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-event-3",
    user_id: "demo",
    title: "Captação no Jardim América",
    description: "Levar briefing de fotos e checklist documental.",
    date: today,
    start_time: "14:30",
    end_time: "15:30",
    type: "captação",
    location: "Jardim América",
    status: "agendado",
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-event-4",
    user_id: "demo",
    title: "Retorno cliente investidor",
    description: "Enviar simulação de rendimento e condomínio.",
    date: today,
    start_time: "17:00",
    end_time: "17:20",
    type: "follow-up",
    location: "WhatsApp",
    status: "agendado",
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];

export const demoTasks: Task[] = [
  {
    id: "demo-task-1",
    user_id: "demo",
    title: "Confirmar visita das 11h",
    description: "Enviar localização e checklist para o cliente.",
    due_date: today,
    due_time: "08:30",
    priority: "alta",
    status: "pendente",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-task-2",
    user_id: "demo",
    title: "Enviar documentação do imóvel",
    description: null,
    due_date: today,
    due_time: "13:00",
    priority: "média",
    status: "pendente",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-task-3",
    user_id: "demo",
    title: "Retornar cliente de financiamento",
    description: null,
    due_date: format(addDays(new Date(), -1), "yyyy-MM-dd"),
    due_time: "16:00",
    priority: "alta",
    status: "pendente",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-task-4",
    user_id: "demo",
    title: "Atualizar roteiro de visitas",
    description: null,
    due_date: today,
    due_time: "18:00",
    priority: "baixa",
    status: "concluída",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-task-5",
    user_id: "demo",
    title: "Separar contrato de proposta",
    description: null,
    due_date: today,
    due_time: "10:00",
    priority: "média",
    status: "concluída",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];

export const demoCommissions: Commission[] = [
  {
    id: "demo-commission-1",
    user_id: "demo-user",
    sale_id: null,
    client: "Marina Lopes",
    property: "Apartamento 1204 - Vista Norte",
    development: "Vista Norte",
    builder: "Construtora Horizonte",
    sale_date: today,
    vgv: 850000,
    total_commission_percent: 4,
    gross_commission: 34000,
    broker_percent: 80,
    broker_commission: 27200,
    discounts: 1200,
    partner_split: 0,
    net_commission: 26000,
    installments_count: 3,
    first_expected_date: today,
    notes: "Construtora paga após assinatura do financiamento.",
    status: "parcialmente recebida",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-commission-2",
    user_id: "demo-user",
    sale_id: null,
    client: "Rafael Andrade",
    property: "Casa Jardim América",
    development: null,
    builder: null,
    sale_date: format(addDays(new Date(), -8), "yyyy-MM-dd"),
    vgv: 1250000,
    total_commission_percent: 5,
    gross_commission: 62500,
    broker_percent: 60,
    broker_commission: 37500,
    discounts: 0,
    partner_split: 7500,
    net_commission: 30000,
    installments_count: 2,
    first_expected_date: format(addDays(new Date(), 12), "yyyy-MM-dd"),
    notes: "Parcela depende da entrada do cliente.",
    status: "confirmada",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-commission-3",
    user_id: "demo-user",
    sale_id: null,
    client: "Investidor Prime",
    property: "Studio Centro",
    development: "Hub Centro",
    builder: "Axis",
    sale_date: null,
    vgv: 520000,
    total_commission_percent: 3.5,
    gross_commission: 18200,
    broker_percent: 100,
    broker_commission: 18200,
    discounts: 0,
    partner_split: 0,
    net_commission: 18200,
    installments_count: 1,
    first_expected_date: format(addDays(new Date(), 45), "yyyy-MM-dd"),
    notes: "Proposta em negociação.",
    status: "em negociação",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];

export const demoCommissionInstallments: CommissionInstallment[] = [
  {
    id: "demo-installment-1",
    user_id: "demo-user",
    commission_id: "demo-commission-1",
    installment_number: 1,
    due_date: today,
    expected_amount: 8666.67,
    received_amount: 6000,
    received_date: today,
    status: "parcialmente recebida",
    payment_method: "PIX",
    notes: "Saldo de R$ 2.666,67 pendente.",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-installment-2",
    user_id: "demo-user",
    commission_id: "demo-commission-1",
    installment_number: 2,
    due_date: format(addDays(new Date(), 30), "yyyy-MM-dd"),
    expected_amount: 8666.67,
    received_amount: 0,
    received_date: null,
    status: "confirmada",
    payment_method: null,
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-installment-3",
    user_id: "demo-user",
    commission_id: "demo-commission-1",
    installment_number: 3,
    due_date: format(addDays(new Date(), 60), "yyyy-MM-dd"),
    expected_amount: 8666.66,
    received_amount: 0,
    received_date: null,
    status: "confirmada",
    payment_method: null,
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-installment-4",
    user_id: "demo-user",
    commission_id: "demo-commission-2",
    installment_number: 1,
    due_date: format(addDays(new Date(), 12), "yyyy-MM-dd"),
    expected_amount: 15000,
    received_amount: 0,
    received_date: null,
    status: "confirmada",
    payment_method: null,
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-installment-5",
    user_id: "demo-user",
    commission_id: "demo-commission-2",
    installment_number: 2,
    due_date: format(addDays(new Date(), 42), "yyyy-MM-dd"),
    expected_amount: 15000,
    received_amount: 0,
    received_date: null,
    status: "confirmada",
    payment_method: null,
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];

export const demoFinancialTransactions: FinancialTransaction[] = [
  {
    id: "demo-finance-1",
    user_id: "demo-user",
    type: "income",
    category: "consultoria",
    description: "Consultoria para avaliação de imóvel",
    amount: 1200,
    due_date: today,
    paid_date: today,
    status: "recebido",
    payment_method: "PIX",
    client_id: null,
    property_id: null,
    sale_id: null,
    commission_id: null,
    is_recurring: false,
    recurrence_rule: null,
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-finance-2",
    user_id: "demo-user",
    type: "expense",
    category: "fotografia",
    description: "Fotógrafo para captação",
    amount: 450,
    due_date: today,
    paid_date: null,
    status: "pendente",
    payment_method: "PIX",
    client_id: null,
    property_id: null,
    sale_id: null,
    commission_id: null,
    is_recurring: false,
    recurrence_rule: null,
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-finance-3",
    user_id: "demo-user",
    type: "expense",
    category: "tráfego pago",
    description: "Campanha Instagram",
    amount: 2340,
    due_date: format(addDays(new Date(), -3), "yyyy-MM-dd"),
    paid_date: format(addDays(new Date(), -3), "yyyy-MM-dd"),
    status: "pago",
    payment_method: "cartão",
    client_id: null,
    property_id: null,
    sale_id: null,
    commission_id: null,
    is_recurring: true,
    recurrence_rule: "mensal",
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-finance-4",
    user_id: "demo-user",
    type: "expense",
    category: "combustível",
    description: "Combustível visitas",
    amount: 180,
    due_date: today,
    paid_date: today,
    status: "pago",
    payment_method: "cartão",
    client_id: null,
    property_id: null,
    sale_id: null,
    commission_id: null,
    is_recurring: false,
    recurrence_rule: null,
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-finance-5",
    user_id: "demo-user",
    type: "expense",
    category: "CRM",
    description: "Assinatura CRM",
    amount: 299,
    due_date: format(addDays(new Date(), 1), "yyyy-MM-dd"),
    paid_date: null,
    status: "pendente",
    payment_method: "cartão",
    client_id: null,
    property_id: null,
    sale_id: null,
    commission_id: null,
    is_recurring: true,
    recurrence_rule: "mensal",
    notes: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];

export const demoMonthlyBudgets: MonthlyBudget[] = [
  {
    id: "demo-budget-1",
    user_id: "demo-user",
    category: "tráfego pago",
    month: format(new Date(), "yyyy-MM-01"),
    limit_amount: 3000,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  },
  {
    id: "demo-budget-2",
    user_id: "demo-user",
    category: "combustível",
    month: format(new Date(), "yyyy-MM-01"),
    limit_amount: 1500,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString()
  }
];
