import { useMemo, useState } from "react";
import { Bookmark, Bot, Check, ChevronRight, Clock3, ExternalLink, Flame, MessageCircle, Newspaper, RefreshCw, Search, Settings2, Share2, Sparkles, Target, TrendingUp, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Skeleton } from "@/components/ui/skeleton";
import { useToast } from "@/components/ui/toast";
import { useClients } from "@/features/clients/use-clients";
import { cn } from "@/lib/utils";
import type { Client, MarketNews } from "@/types/database";
import { MarketNewsSettingsDialog } from "./MarketNewsSettingsDialog";
import { NewsStoryDialog } from "./NewsStoryDialog";
import { useMarketNews } from "./use-market-news";

const categories = ["todas", "litoral", "mercado", "crédito", "investimento", "legislação"] as const;
type View = "radar" | "salvas" | "histórico";

export function MarketNewsPage() {
  const { news, isLoading, error, setState, refresh, settings, saveSettings, isSavingSettings } = useMarketNews();
  const crm = useClients();
  const { toast } = useToast();
  const [view, setView] = useState<View>("radar");
  const [category, setCategory] = useState<(typeof categories)[number]>("todas");
  const [query, setQuery] = useState("");
  const [selectedId, setSelectedId] = useState<string>();
  const [story, setStory] = useState<MarketNews>();
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [refreshing, setRefreshing] = useState(false);
  const selected = news.find((item) => item.id === selectedId);
  const briefing = settings.enabled ? ([...news].sort((a, b) => {
    const aPreferred = Number(settings.categories.includes(a.category) && settings.regions.includes(a.region));
    const bPreferred = Number(settings.categories.includes(b.category) && settings.regions.includes(b.region));
    return (bPreferred - aPreferred) || (b.relevance_score - a.relevance_score);
  })[0]) : undefined;
  const clients = useMemo(() => suggestedClients(crm.clients), [crm.clients]);
  const filtered = useMemo(() => news.filter((item) => {
    const matchesView = view === "salvas" ? item.saved : view === "radar" ? !item.read || item.relevance_score >= 90 : true;
    return matchesView && (category === "todas" || item.category === category) && `${item.title} ${item.summary} ${item.region} ${item.audiences.join(" ")}`.toLowerCase().includes(query.toLowerCase());
  }), [news, view, category, query]);
  const today = news.filter((item) => Date.now() - new Date(item.published_at).getTime() < 86400000).length;

  async function open(item: MarketNews) { setSelectedId(item.id); if (!item.read) await setState({ id: item.id, patch: { read: true } }); }
  async function toggleSaved(item: MarketNews) { await setState({ id: item.id, patch: { saved: !item.saved } }); toast({ title: item.saved ? "Removida das salvas." : "Notícia salva." }); }
  async function copyArgument(item: MarketNews) { await navigator.clipboard.writeText(item.whatsapp_script); toast({ title: "Mensagem copiada para o WhatsApp." }); }
  async function update() { setRefreshing(true); try { await refresh(); toast({ title: "Radar atualizado." }); } catch { toast({ title: "A atualização automática ainda não está configurada.", variant: "error" }); } finally { setRefreshing(false); } }

  return <div className="mx-auto w-full max-w-[1600px] space-y-5">
    <header className="relative overflow-hidden rounded-[1.75rem] border bg-[#07111d] px-5 py-6 text-white shadow-[0_18px_50px_rgba(6,15,25,.18)] sm:px-7 sm:py-8">
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(4,12,21,.97),rgba(4,12,21,.72),rgba(4,12,21,.92)),url('/brand/capao-sunset.png')] bg-cover bg-center opacity-90" />
      <div className="relative flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.16em] text-amber-200"><TrendingUp className="h-4 w-4" />Inteligência comercial</div><h1 className="text-3xl font-semibold sm:text-4xl">Radar do mercado</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-white/62">Entenda o cenário, prepare a conversa e transforme informação em oportunidade.</p></div><div className="grid grid-cols-2 gap-2"><Button variant="outline" className="border-white/15 bg-white/5 text-white hover:bg-white/10" onClick={() => setSettingsOpen(true)}><Settings2 className="h-4 w-4" />Preferências</Button><Button variant="outline" className="border-white/15 bg-white/5 text-white hover:bg-white/10" disabled={refreshing} onClick={() => void update()}><RefreshCw className={cn("h-4 w-4", refreshing && "animate-spin")} />Atualizar</Button></div></div>
    </header>

    {briefing && <section className="overflow-hidden rounded-3xl border bg-card shadow-[0_10px_34px_rgba(15,23,42,.06)]"><div className="grid lg:grid-cols-[1.2fr_.8fr]"><div className="p-5 sm:p-6"><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-[10px] font-bold uppercase text-primary">Leitura do dia</span><ImpactBadge impact={briefing.market_impact} /><span className="text-xs text-muted-foreground">Relevância {briefing.relevance_score}%</span></div><h2 className="mt-4 max-w-3xl text-xl font-semibold leading-snug sm:text-2xl">{briefing.title}</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-muted-foreground">{briefing.sales_argument}</p><div className="mt-4 flex flex-wrap gap-2">{briefing.audiences.map((audience) => <Audience key={audience} value={audience} />)}</div></div><div className="flex flex-col justify-between border-t bg-muted/35 p-5 lg:border-l lg:border-t-0"><div><p className="text-xs font-bold uppercase text-muted-foreground">Pergunta para abrir a conversa</p><p className="mt-2 text-base font-semibold leading-6">“{briefing.discovery_question}”</p></div><div className="mt-5 grid grid-cols-2 gap-2"><Button variant="outline" onClick={() => void open(briefing)}><Bot className="h-4 w-4" />Ver plano</Button><Button onClick={() => setStory(briefing)}><Sparkles className="h-4 w-4" />Criar story</Button></div></div></div></section>}

    <section className="grid grid-cols-3 gap-2 sm:gap-3"><Summary label="No radar" value={news.length} icon={Newspaper} onClick={() => setView("radar")} active={view === "radar"} /><Summary label="Hoje" value={today} icon={Clock3} onClick={() => setView("histórico")} /><Summary label="Salvas" value={news.filter((item) => item.saved).length} icon={Bookmark} onClick={() => setView("salvas")} active={view === "salvas"} /></section>

    <section className="space-y-3"><div className="grid gap-3 lg:grid-cols-[auto_1fr]"><div className="grid grid-cols-3 rounded-2xl border bg-card p-1">{(["radar", "salvas", "histórico"] as View[]).map((item) => <button key={item} onClick={() => setView(item)} className={cn("rounded-xl px-4 py-2.5 text-xs font-semibold capitalize transition", view === item && "bg-foreground text-background shadow-sm")}>{item}</button>)}</div><div className="relative"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} className="h-12 rounded-2xl bg-card pl-10" placeholder="Buscar assunto, cidade, região ou público" /></div></div><div className="flex gap-2 overflow-x-auto pb-1 scrollbar-none">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={cn("shrink-0 rounded-full border bg-card px-4 py-2 text-xs font-semibold capitalize transition", category === item && "border-primary bg-primary text-primary-foreground")}>{item}</button>)}</div></section>

    {error && <div className="rounded-2xl border border-destructive/30 bg-destructive/5 p-4 text-sm">Não foi possível atualizar as notícias. O histórico disponível continua acessível.</div>}
    {isLoading ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{Array.from({ length: 6 }).map((_, index) => <Skeleton key={index} className="h-80 rounded-3xl" />)}</div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((item) => <NewsCard key={item.id} item={item} onOpen={() => void open(item)} onSave={() => void toggleSaved(item)} onStory={() => setStory(item)} />)}</div>}
    {!isLoading && !filtered.length && <div className="rounded-3xl border bg-card px-5 py-14 text-center"><Newspaper className="mx-auto h-8 w-8 text-muted-foreground" /><p className="mt-3 font-semibold">Nenhuma notícia neste filtro</p><p className="mt-1 text-sm text-muted-foreground">Tente outro tema ou volte para o radar.</p><Button variant="outline" className="mt-4" onClick={() => { setView("radar"); setCategory("todas"); setQuery(""); }}>Limpar filtros</Button></div>}

    <Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelectedId(undefined)}>{selected && <DialogContent className="sm:max-w-3xl"><DialogHeader><div className="mb-2 flex flex-wrap items-center gap-2 text-xs font-bold uppercase text-primary"><span>{selected.category}</span><span>•</span><span>{selected.region}</span><ImpactBadge impact={selected.market_impact} /></div><DialogTitle className="pr-7 text-2xl leading-tight">{selected.title}</DialogTitle><DialogDescription>{selected.source_name} · {new Date(selected.published_at).toLocaleDateString("pt-BR")}</DialogDescription></DialogHeader><p className="text-sm leading-6 text-muted-foreground">{selected.summary}</p><div className="grid gap-3 md:grid-cols-2"><Insight icon={Bot} title="Como usar na venda" text={selected.sales_argument} /><Insight icon={MessageCircle} title="Mensagem pronta" text={selected.whatsapp_script} /></div><section className="rounded-2xl border bg-muted/35 p-4"><div className="flex items-center gap-2"><Target className="h-4 w-4 text-primary" /><h3 className="font-semibold">Plano de conversa</h3></div><div className="mt-3 grid gap-3 sm:grid-cols-3"><TalkStep label="Objeção provável" text={selected.objection} /><TalkStep label="Resposta sugerida" text={selected.objection_response} /><TalkStep label="Pergunta para avançar" text={selected.discovery_question} /></div></section>{clients.length > 0 && <section><div className="mb-3 flex items-center gap-2"><Users className="h-4 w-4 text-primary" /><h3 className="font-semibold">Clientes para abordar</h3></div><div className="grid gap-2 sm:grid-cols-3">{clients.map((client) => <ClientSuggestion key={client.id} client={client} message={selected.whatsapp_script} />)}</div></section>}<div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Button variant="outline" asChild><a href={selected.source_url} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4" />Fonte</a></Button><Button variant="outline" onClick={() => void copyArgument(selected)}><MessageCircle className="h-4 w-4" />Copiar</Button><Button variant="outline" onClick={() => void toggleSaved(selected)}>{selected.saved ? <Check className="h-4 w-4" /> : <Bookmark className="h-4 w-4" />}{selected.saved ? "Salva" : "Salvar"}</Button><Button onClick={() => setStory(selected)}><Sparkles className="h-4 w-4" />Story</Button></div></DialogContent>}</Dialog>
    <MarketNewsSettingsDialog open={settingsOpen} settings={settings} saving={isSavingSettings} onOpenChange={setSettingsOpen} onSave={async (value) => { try { await saveSettings(value); setSettingsOpen(false); toast({ title: "Preferências do radar atualizadas." }); } catch { toast({ title: "Não foi possível salvar as preferências.", variant: "error" }); } }} />
    <NewsStoryDialog news={story} open={Boolean(story)} onOpenChange={(open) => !open && setStory(undefined)} />
  </div>;
}

function NewsCard({ item, onOpen, onSave, onStory }: { item: MarketNews; onOpen: () => void; onSave: () => void; onStory: () => void }) { return <Card className={cn("overflow-hidden border-0 shadow-[0_8px_30px_rgba(15,23,42,.07)] ring-1 ring-border/70 transition hover:-translate-y-0.5 hover:shadow-[0_14px_36px_rgba(15,23,42,.1)]", !item.read && "ring-primary/35")}><CardContent className="flex h-full flex-col p-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><span className="rounded-full bg-primary/10 px-2.5 py-1 text-[10px] font-bold uppercase text-primary">{item.category}</span><ImpactBadge impact={item.market_impact} /></div><button onClick={onSave} aria-label="Salvar notícia" className={cn("grid h-9 w-9 place-items-center rounded-full border transition", item.saved && "border-primary bg-primary/10 text-primary")}><Bookmark className={cn("h-4 w-4", item.saved && "fill-current")} /></button></div><button onClick={onOpen} className="mt-4 block w-full flex-1 text-left"><h2 className="text-lg font-semibold leading-snug">{item.title}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-muted-foreground">{item.summary}</p><div className="mt-4 flex flex-wrap gap-1.5">{item.audiences.map((audience) => <Audience key={audience} value={audience} />)}</div><div className="mt-4 flex items-center justify-between border-t pt-4 text-xs text-muted-foreground"><span>{item.source_name}</span><span>{new Date(item.published_at).toLocaleDateString("pt-BR")}</span></div></button><div className="mt-4 grid grid-cols-2 gap-2"><Button size="sm" variant="outline" onClick={onOpen}><Bot className="h-4 w-4" />Plano de venda</Button><Button size="sm" onClick={onStory}><Share2 className="h-4 w-4" />Criar story</Button></div></CardContent></Card>; }
function Summary({ label, value, icon: Icon, onClick, active }: { label: string; value: number; icon: React.ElementType; onClick: () => void; active?: boolean }) { return <button onClick={onClick} className={cn("rounded-2xl border bg-card p-3 text-left shadow-sm transition hover:border-primary/40 sm:p-4", active && "border-primary/45 bg-primary/5")}><Icon className="h-4 w-4 text-primary" /><p className="mt-3 text-2xl font-semibold tabular-nums">{value}</p><p className="mt-0.5 text-[10px] font-semibold uppercase text-muted-foreground sm:text-xs">{label}</p></button>; }
function ImpactBadge({ impact }: { impact: MarketNews["market_impact"] }) { return <span className={cn("rounded-full px-2 py-1 text-[9px] font-bold uppercase", impact === "positivo" ? "bg-emerald-500/10 text-emerald-700 dark:text-emerald-300" : impact === "atenção" ? "bg-amber-500/12 text-amber-700 dark:text-amber-200" : "bg-muted text-muted-foreground")}>{impact}</span>; }
function Audience({ value }: { value: MarketNews["audiences"][number] }) { return <span className="rounded-full border bg-background px-2.5 py-1 text-[10px] font-semibold capitalize text-muted-foreground">{value}</span>; }
function Insight({ icon: Icon, title, text }: { icon: React.ElementType; title: string; text: string }) { return <section className="rounded-2xl border bg-card p-4"><div className="flex items-center gap-2"><Icon className="h-4 w-4 text-primary" /><h3 className="font-semibold">{title}</h3></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{text}</p></section>; }
function TalkStep({ label, text }: { label: string; text: string }) { return <div className="rounded-xl bg-background p-3"><p className="text-[10px] font-bold uppercase text-muted-foreground">{label}</p><p className="mt-1.5 text-sm leading-5">{text}</p></div>; }
function ClientSuggestion({ client, message }: { client: Client; message: string }) { const phone = (client.whatsapp || client.phone || "").replace(/\D/g, ""); return <div className="rounded-2xl border bg-card p-3"><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate text-sm font-semibold">{client.name}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">{client.city || client.property_profile || "Perfil em construção"}</p></div>{client.temperature === "quente" && <Flame className="h-4 w-4 shrink-0 text-amber-600" />}</div>{phone ? <Button asChild variant="outline" size="sm" className="mt-3 w-full"><a href={`https://wa.me/${phone}?text=${encodeURIComponent(message)}`} target="_blank" rel="noreferrer"><MessageCircle className="h-4 w-4" />Conversar<ChevronRight className="ml-auto h-4 w-4" /></a></Button> : <p className="mt-3 text-xs text-muted-foreground">WhatsApp não informado</p>}</div>; }
function suggestedClients(clients: Client[]) { const rank = { quente: 0, morno: 1, frio: 2 } as const; return clients.filter((client) => client.status !== "perdido" && client.status !== "venda realizada" && client.status !== "pós-venda").sort((a, b) => (rank[a.temperature ?? "frio"] - rank[b.temperature ?? "frio"]) || String(a.next_follow_up ?? "9999").localeCompare(String(b.next_follow_up ?? "9999"))).slice(0, 3); }
