import type { MarketNews } from "@/types/database";

export const demoMarketNews: MarketNews[] = [
  {
    id: "demo-news-litoral-2026",
    title: "Capão da Canoa e Xangri-Lá concentram 54% das vendas do Litoral Norte",
    summary: "O Litoral Norte movimentou R$ 3,74 bilhões no primeiro semestre de 2026. Capão da Canoa e Xangri-Lá responderam juntas por cerca de 54% das vendas da região.",
    source_name: "SECOVI/RS",
    source_url: "https://www.secovi-rs.com.br/site/default.asp?ID=814330&SecaoID=494829&SubsecaoID=819354&Template=../artigosnoticias/user_exibir.asp&TroncoID=083154",
    image_url: null,
    published_at: "2026-08-11T12:00:00-03:00",
    category: "litoral",
    region: "Litoral Norte/RS",
    relevance_score: 98,
    audiences: ["comprador", "investidor", "proprietário"],
    market_impact: "positivo",
    sales_argument: "Os dados reforçam que Capão da Canoa e Xangri-Lá não dependem apenas da temporada: elas concentram mais da metade do volume negociado no litoral. Para o comprador, isso sinaliza mercado ativo e maior liquidez relativa na região.",
    objection: "Será que o litoral só vende bem no verão?",
    objection_response: "O levantamento mostra volume relevante já no primeiro semestre e concentração de negócios nas duas cidades. Isso indica atividade além da alta temporada, sem garantir valorização futura.",
    discovery_question: "Você busca um imóvel para uso próprio, renda ou valorização no litoral?",
    whatsapp_script: "Saiu um dado importante do mercado: Capão da Canoa e Xangri-Lá concentraram 54% das vendas do Litoral Norte no primeiro semestre. Isso ajuda a entender por que imóveis bem localizados nessas cidades seguem com procura. Quer que eu te mostre opções dentro do seu perfil?",
    story_headline: "54% das vendas do litoral estão em duas cidades",
    story_body: "Capão da Canoa e Xangri-Lá concentraram mais da metade das negociações do Litoral Norte no 1º semestre de 2026.",
    story_cta: "Quer investir onde o mercado está girando? Fale comigo.",
    created_at: "2026-09-28T08:00:00-03:00"
  },
  {
    id: "demo-news-brasil-2026",
    title: "Vendas de imóveis novos avançam 5,4% no primeiro semestre",
    summary: "Segundo a CBIC, 226.536 unidades residenciais novas foram comercializadas no país entre janeiro e junho de 2026, alta de 5,4% sobre o mesmo período de 2025.",
    source_name: "CBIC",
    source_url: "https://cbic.org.br/vendas-de-imoveis-avancam-54-no-primeiro-semestre-e-mcmv-registra-participacao-recorde/",
    image_url: null,
    published_at: "2026-08-24T12:00:00-03:00",
    category: "mercado",
    region: "Brasil",
    relevance_score: 91,
    audiences: ["comprador", "investidor"],
    market_impact: "positivo",
    sales_argument: "Mesmo com crédito mais seletivo, o mercado nacional de imóveis novos cresceu. O dado ajuda a responder ao cliente que espera uma paralisação geral: a demanda continua existindo, mas escolhe melhor localização, produto e condição de pagamento.",
    objection: "Com os juros atuais, não é melhor esperar?",
    objection_response: "O mercado continuou avançando, mas a decisão precisa comparar produto, entrada, parcela e prazo. O dado mostra movimento, não uma promessa de ganho.",
    discovery_question: "O que pesa mais para você hoje: entrada, parcela ou prazo de pagamento?",
    whatsapp_script: "A CBIC divulgou alta de 5,4% nas vendas de imóveis novos no primeiro semestre. Mesmo com juros elevados, bons produtos continuam encontrando comprador. Posso separar opções com melhor relação entre localização, condição e potencial de valorização para você.",
    story_headline: "Mercado de imóveis novos cresce 5,4%",
    story_body: "Foram 226 mil unidades vendidas no Brasil no primeiro semestre de 2026, segundo a CBIC.",
    story_cta: "O melhor momento começa com a escolha certa.",
    created_at: "2026-09-28T08:00:00-03:00"
  },
  {
    id: "demo-news-credito-2026",
    title: "Crédito para média e alta renda passa por ajustes no novo modelo",
    summary: "Instituições financeiras discutem ajustes nas regras do crédito imobiliário para compradores de média e alta renda, em um cenário de juros ainda elevados.",
    source_name: "SECOVI/RS",
    source_url: "https://www.secovi-rs.com.br/site/default.asp?ID=549145&SecaoID=494829&SubsecaoID=819354&Template=../artigosnoticias/user_exibir.asp&TroncoID=083154",
    image_url: null,
    published_at: "2026-09-08T12:00:00-03:00",
    category: "crédito",
    region: "Brasil",
    relevance_score: 86,
    audiences: ["comprador", "investidor"],
    market_impact: "atenção",
    sales_argument: "A notícia não significa falta total de crédito. Ela mostra que simulação e estratégia de pagamento ganharam importância. O corretor pode comparar financiamento, entrada, parcelamento direto e negociação para encontrar a estrutura mais adequada ao cliente.",
    objection: "O financiamento imobiliário está impossível?",
    objection_response: "Não necessariamente. As condições ficaram mais seletivas, por isso simulação, entrada e alternativas de parcelamento precisam ser avaliadas caso a caso.",
    discovery_question: "Você já definiu o valor de entrada e uma parcela mensal confortável?",
    whatsapp_script: "As regras do crédito imobiliário estão passando por ajustes, principalmente para média e alta renda. Antes de descartar uma compra, vale comparar entrada, financiamento e parcelamento direto. Posso montar essa leitura com você e buscar imóveis compatíveis.",
    story_headline: "Crédito mudou. Estratégia virou diferencial.",
    story_body: "Com juros altos e novas regras, comparar formas de pagamento ficou ainda mais importante na compra do imóvel.",
    story_cta: "Converse com quem conhece as alternativas do mercado.",
    created_at: "2026-09-28T08:00:00-03:00"
  }
];
