import { useMemo, useState } from "react";
import { CreditCard, FileImage, Library, MoreHorizontal, ShieldCheck, Users, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/components/ui/toast";
import { cn } from "@/lib/utils";
import { useSaasAdmin, type MaterialInput, type SaasMaterial, type SaasMember, type SaasPayment, type SaasPlan } from "./use-saas-admin";

type AdminTab = "users" | "materials" | "payments" | "plans";
const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });

export function AdminPage() {
  const admin = useSaasAdmin();
  const { toast } = useToast();
  const [tab, setTab] = useState<AdminTab>("users");
  const [materialOpen, setMaterialOpen] = useState(false);
  const [editingPlan, setEditingPlan] = useState<SaasPlan | null>(null);
  const active = admin.members.filter((member) => member.status === "active").length;
  const overdue = admin.members.filter((member) => member.status === "past_due").length;
  const mrr = admin.members.filter((member) => member.status === "active").reduce((sum, member) => sum + (admin.plans.find((plan) => plan.id === member.plan_id)?.monthly_price ?? 0), 0);

  if (admin.isLoading) return <div className="rounded-3xl border bg-card p-8 text-sm text-muted-foreground">Carregando controle do SaaS...</div>;
  if (!admin.isAdmin) return <div className="mx-auto max-w-lg rounded-3xl border bg-card p-8 text-center"><ShieldCheck className="mx-auto h-9 w-9 text-muted-foreground" /><h1 className="mt-4 text-2xl font-semibold">Área restrita</h1><p className="mt-2 text-sm text-muted-foreground">Somente o administrador principal pode acessar usuários, pagamentos e distribuição de materiais.</p></div>;

  const tabs: Array<{ id: AdminTab; label: string; icon: React.ElementType }> = [
    { id: "users", label: "Assinantes", icon: Users }, { id: "materials", label: "Materiais", icon: Library }, { id: "payments", label: "Pagamentos", icon: WalletCards }, { id: "plans", label: "Planos", icon: CreditCard }
  ];

  return <div className="mx-auto w-full max-w-[1580px] space-y-5">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase text-primary">Gestão do SaaS</p><h1 className="mt-1 text-3xl font-semibold">Super Admin</h1><p className="mt-1 text-sm text-muted-foreground">Assinantes, receita recorrente, acesso e conteúdo distribuído.</p></div>{tab === "materials" && <Button onClick={() => setMaterialOpen(true)}><FileImage className="h-4 w-4" />Novo material</Button>}</header>
    <section className="grid grid-cols-2 gap-3 xl:grid-cols-4"><AdminMetric label="Assinantes ativos" value={String(active)} detail={`${admin.members.length} contas cadastradas`} /><AdminMetric label="Receita recorrente" value={brl.format(mrr)} detail="MRR estimado pelos planos" /><AdminMetric label="Pagamento atrasado" value={String(overdue)} detail="requer atenção" attention={overdue > 0} /><AdminMetric label="Materiais publicados" value={String(admin.materials.filter((item) => item.published).length)} detail="disponíveis nas agendas" /></section>
    <nav className="flex gap-1 overflow-x-auto rounded-2xl border bg-card p-1.5 [scrollbar-width:none]">{tabs.map((item) => <button key={item.id} type="button" onClick={() => setTab(item.id)} className={cn("inline-flex min-h-11 shrink-0 items-center gap-2 rounded-xl px-4 text-sm font-semibold text-muted-foreground transition", tab === item.id && "bg-foreground text-background shadow-sm")}><item.icon className="h-4 w-4" />{item.label}</button>)}</nav>
    {tab === "users" && <UsersPanel members={admin.members} plans={admin.plans} onStatus={async (member, status) => { await admin.updateMember.mutateAsync({ id: member.id, status }); toast({ title: `Acesso de ${member.name} atualizado.` }); }} />}
    {tab === "materials" && <MaterialsPanel materials={admin.materials} onToggle={async (id, published) => { await admin.toggleMaterial.mutateAsync({ id, published }); toast({ title: published ? "Material publicado nas agendas." : "Material retirado das agendas." }); }} />}
    {tab === "payments" && <PaymentsPanel payments={admin.payments} onStatus={async (id, status) => { await admin.updatePayment.mutateAsync({ id, status }); toast({ title: "Status da cobrança atualizado." }); }} />}
    {tab === "plans" && <PlansPanel plans={admin.plans} onEdit={setEditingPlan} />}
    <MaterialDialog open={materialOpen} pending={admin.createMaterial.isPending} onOpenChange={setMaterialOpen} onSubmit={async (input) => { await admin.createMaterial.mutateAsync(input); setMaterialOpen(false); toast({ title: input.published ? "Material publicado para os assinantes." : "Material salvo como rascunho." }); }} />
    <PlanDialog plan={editingPlan} pending={admin.updatePlan.isPending} onOpenChange={(open) => !open && setEditingPlan(null)} onSubmit={async (id, input) => { await admin.updatePlan.mutateAsync({ id, input }); setEditingPlan(null); toast({ title: "Plano atualizado." }); }} />
  </div>;
}

function AdminMetric({ label, value, detail, attention }: { label: string; value: string; detail: string; attention?: boolean }) { return <article className="rounded-2xl border bg-card p-4 shadow-sm"><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className={cn("mt-3 text-2xl font-semibold tabular-nums", attention && "text-destructive")}>{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p></article>; }

function UsersPanel({ members, plans, onStatus }: { members: SaasMember[]; plans: SaasPlan[]; onStatus: (member: SaasMember, status: SaasMember["status"]) => Promise<void> }) {
  const [search, setSearch] = useState("");
  const visible = useMemo(() => members.filter((member) => `${member.name} ${member.email} ${member.city}`.toLowerCase().includes(search.toLowerCase())), [members, search]);
  return <section className="rounded-2xl border bg-card"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><h2 className="font-semibold">Controle de assinantes</h2><p className="text-xs text-muted-foreground">Ative, suspenda e acompanhe cada conta.</p></div><Input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar nome, e-mail ou cidade" className="max-w-sm" /></div><div className="divide-y">{visible.map((member) => { const plan = plans.find((item) => item.id === member.plan_id); return <div key={member.id} className="grid gap-3 p-4 sm:grid-cols-[minmax(0,1fr)_150px_130px_160px] sm:items-center"><div className="min-w-0"><p className="truncate text-sm font-semibold">{member.name}</p><p className="truncate text-xs text-muted-foreground">{member.email} · {member.city}</p></div><div><p className="text-xs font-semibold">{plan?.name ?? "Sem plano"}</p><p className="text-[11px] text-muted-foreground">Renova {formatDate(member.renewal)}</p></div><StatusBadge status={member.status} /><select value={member.status} onChange={(event) => void onStatus(member, event.target.value as SaasMember["status"])} className="h-10 rounded-xl border bg-background px-3 text-xs font-semibold"><option value="trialing">Teste</option><option value="active">Ativo</option><option value="past_due">Inadimplente</option><option value="suspended">Suspenso</option><option value="canceled">Cancelado</option></select></div>; })}</div></section>;
}

function MaterialsPanel({ materials, onToggle }: { materials: SaasMaterial[]; onToggle: (id: string, published: boolean) => Promise<void> }) { return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{materials.map((material) => <article key={material.id} className="overflow-hidden rounded-2xl border bg-card"><div className="aspect-[16/7] bg-muted">{material.thumbnail_url ? <img src={material.thumbnail_url} alt="" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center"><FileImage className="h-8 w-8 text-muted-foreground" /></div>}</div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-[10px] font-semibold uppercase text-primary">{material.category}</span><h3 className="mt-1 font-semibold">{material.title}</h3></div><MoreHorizontal className="h-4 w-4 text-muted-foreground" /></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-muted-foreground">{material.description}</p><div className="mt-4 flex items-center justify-between"><span className={cn("rounded-full px-2.5 py-1 text-[10px] font-semibold", material.published ? "bg-emerald-500/10 text-emerald-600" : "bg-muted text-muted-foreground")}>{material.published ? "Publicado" : "Rascunho"}</span><Button size="sm" variant="outline" onClick={() => void onToggle(material.id, !material.published)}>{material.published ? "Retirar" : "Publicar"}</Button></div></div></article>)}</div>; }

function PaymentsPanel({ payments, onStatus }: { payments: SaasPayment[]; onStatus: (id: string, status: SaasPayment["status"]) => Promise<void> }) { return <section className="rounded-2xl border bg-card"><div className="border-b p-4"><h2 className="font-semibold">Cobranças e pagamentos</h2><p className="text-xs text-muted-foreground">Visão operacional das mensalidades.</p></div><div className="divide-y">{payments.map((payment) => <div key={payment.id} className="grid gap-2 p-4 sm:grid-cols-[minmax(0,1fr)_120px_130px_120px_150px] sm:items-center"><div><p className="text-sm font-semibold">{payment.member_name}</p><p className="text-xs text-muted-foreground">{payment.payment_method}</p></div><p className="text-sm font-semibold tabular-nums">{brl.format(payment.amount)}</p><p className="text-xs text-muted-foreground">Vence {formatDate(payment.due_date)}</p><StatusBadge status={payment.status} /><select value={payment.status} onChange={(event) => void onStatus(payment.id, event.target.value as SaasPayment["status"])} className="h-10 rounded-xl border bg-background px-3 text-xs font-semibold"><option value="pending">Pendente</option><option value="paid">Pago</option><option value="overdue">Atrasado</option><option value="refunded">Estornado</option><option value="canceled">Cancelado</option></select></div>)}</div></section>; }

function PlansPanel({ plans, onEdit }: { plans: SaasPlan[]; onEdit: (plan: SaasPlan) => void }) { return <div className="grid gap-4 lg:grid-cols-3">{plans.map((plan) => <article key={plan.id} className="rounded-2xl border bg-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase text-primary">{plan.name}</p><span className={cn("rounded-full px-2 py-1 text-[10px] font-semibold", plan.active ? "bg-emerald-500/10 text-emerald-600" : "bg-muted text-muted-foreground")}>{plan.active ? "Ativo" : "Inativo"}</span></div><p className="mt-4 text-3xl font-semibold">{brl.format(plan.monthly_price)}<span className="text-xs font-medium text-muted-foreground">/mês</span></p><p className="mt-2 text-sm text-muted-foreground">{plan.description}</p><div className="mt-5 space-y-2">{plan.features.map((feature) => <p key={feature} className="flex items-center gap-2 text-xs"><span className="grid h-5 w-5 place-items-center rounded-full bg-emerald-500/10 text-emerald-600">✓</span>{feature}</p>)}</div><Button variant="outline" className="mt-5 w-full" onClick={() => onEdit(plan)}>Editar plano</Button></article>)}</div>; }

function MaterialDialog({ open, pending, onOpenChange, onSubmit }: { open: boolean; pending: boolean; onOpenChange: (open: boolean) => void; onSubmit: (input: MaterialInput) => Promise<void> }) {
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); await onSubmit({ title: String(form.get("title")), description: String(form.get("description") ?? ""), category: String(form.get("category")), material_type: String(form.get("materialType")) as MaterialInput["material_type"], thumbnail_url: String(form.get("thumbnailUrl") ?? ""), external_url: String(form.get("externalUrl")), target_plan_ids: [], published: form.get("published") === "on" }); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Distribuir novo material</DialogTitle><DialogDescription>Publique uma imagem, vídeo, PDF ou pasta para aparecer nas agendas dos assinantes.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><div><Label htmlFor="material-title">Nome do material</Label><Input id="material-title" name="title" className="mt-2" required /></div><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="material-category">Categoria</Label><Input id="material-category" name="category" className="mt-2" placeholder="Marketing" required /></div><div><Label htmlFor="material-type">Tipo</Label><select id="material-type" name="materialType" className="mt-2 h-12 w-full rounded-2xl border bg-background px-4 text-sm"><option value="image">Imagem</option><option value="video">Vídeo</option><option value="pdf">PDF</option><option value="drive">Drive</option><option value="link">Link</option></select></div></div><div><Label htmlFor="material-url">Link do arquivo ou pasta</Label><Input id="material-url" name="externalUrl" type="url" className="mt-2" required /></div><div><Label htmlFor="material-cover">Link da capa</Label><Input id="material-cover" name="thumbnailUrl" type="url" className="mt-2" /></div><div><Label htmlFor="material-description">Descrição</Label><Textarea id="material-description" name="description" className="mt-2" /></div><label className="flex items-center gap-3 rounded-xl border p-3 text-sm font-semibold"><input type="checkbox" name="published" defaultChecked className="h-4 w-4 accent-primary" />Publicar agora para os assinantes</label><Button disabled={pending}>{pending ? "Publicando..." : "Salvar material"}</Button></form></DialogContent></Dialog>;
}

function PlanDialog({ plan, pending, onOpenChange, onSubmit }: { plan: SaasPlan | null; pending: boolean; onOpenChange: (open: boolean) => void; onSubmit: (id: string, input: Partial<SaasPlan>) => Promise<void> }) {
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!plan) return; const form = new FormData(event.currentTarget); await onSubmit(plan.id, { name: String(form.get("name")), description: String(form.get("description") ?? ""), monthly_price: Number(form.get("monthlyPrice")), annual_price: Number(form.get("annualPrice")), active: form.get("active") === "on" }); }
  return <Dialog open={Boolean(plan)} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Editar plano</DialogTitle><DialogDescription>Atualize preço, descrição e disponibilidade comercial.</DialogDescription></DialogHeader>{plan && <form key={plan.id} onSubmit={submit} className="grid gap-4"><div><Label htmlFor="plan-name">Nome</Label><Input id="plan-name" name="name" defaultValue={plan.name} className="mt-2" required /></div><div className="grid grid-cols-2 gap-3"><div><Label htmlFor="plan-monthly">Mensal</Label><Input id="plan-monthly" name="monthlyPrice" type="number" min="0" step="0.01" defaultValue={plan.monthly_price} className="mt-2" required /></div><div><Label htmlFor="plan-annual">Anual</Label><Input id="plan-annual" name="annualPrice" type="number" min="0" step="0.01" defaultValue={plan.annual_price} className="mt-2" required /></div></div><div><Label htmlFor="plan-description">Descrição</Label><Textarea id="plan-description" name="description" defaultValue={plan.description} className="mt-2" /></div><label className="flex items-center gap-3 rounded-xl border p-3 text-sm font-semibold"><input type="checkbox" name="active" defaultChecked={plan.active} className="h-4 w-4 accent-primary" />Plano disponível para novas assinaturas</label><Button disabled={pending}>{pending ? "Salvando..." : "Salvar plano"}</Button></form>}</DialogContent></Dialog>;
}

function StatusBadge({ status }: { status: string }) { const label: Record<string, string> = { active: "Ativo", trialing: "Em teste", past_due: "Inadimplente", suspended: "Suspenso", canceled: "Cancelado", paid: "Pago", pending: "Pendente", overdue: "Atrasado", refunded: "Estornado" }; return <span className={cn("w-fit rounded-full px-2.5 py-1 text-[10px] font-semibold", ["active", "paid"].includes(status) ? "bg-emerald-500/10 text-emerald-600" : ["past_due", "overdue", "suspended"].includes(status) ? "bg-destructive/10 text-destructive" : "bg-muted text-muted-foreground")}>{label[status] ?? status}</span>; }
function formatDate(value: string) { if (!value) return "—"; return new Date(`${value.slice(0, 10)}T12:00:00`).toLocaleDateString("pt-BR"); }
