import { useEffect, useState } from "react";
import { BarChart3, Boxes, CreditCard, FileImage, Gift, Library, Link2, Megaphone, MoreHorizontal, ServerCog, ShieldCheck, Upload, UserRoundX, Users, WalletCards } from "lucide-react";
import { Button } from "@/components/ui/button";
import { ImageUploadField } from "@/components/ui/image-upload-field";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/components/ui/toast";
import { cn } from "@/lib/utils";
import { useAuth } from "@/features/auth/auth-context";
import { saveImageAsset } from "@/lib/image-assets";
import { useSaasAdmin, type MaterialInput, type SaasBillingRequest, type SaasDeletionRequest, type SaasMaterial, type SaasMember, type SaasPayment, type SaasPlan } from "./use-saas-admin";
import { GiveawayPanel } from "./GiveawayPanel";
import { OperationsPanel } from "./OperationsPanel";
import { SubscribersPanel } from "./SubscribersPanel";

type AdminTab = "overview" | "users" | "payments" | "plans" | "materials" | "giveaways" | "operations" | "privacy";
const brl = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const planFeatures = ["Agenda", "Clientes", "Foco", "Materiais", "Meus Arquivos", "Financeiro", "Metas", "Edifícios", "Condomínios", "Mercado", "Mídia da Cidade", "Suporte prioritário"];
const essentialFeatures = ["Agenda", "Clientes", "Foco", "Materiais", "Meus Arquivos"];
const professionalFeatures = [...essentialFeatures, "Financeiro", "Metas", "Edifícios", "Condomínios", "Mercado", "Mídia da Cidade"];

function hasPlanFeature(plan: SaasPlan, feature: string) {
  if (plan.features.includes(feature)) return true;
  if (feature === "Agenda" && plan.features.includes("Agenda completa")) return true;
  if (feature === "Clientes" && plan.features.includes("CRM de clientes")) return true;
  if (feature === "Suporte prioritário" && plan.features.includes("Suporte")) return true;
  if (plan.features.includes("Tudo do Profissional") && professionalFeatures.includes(feature)) return true;
  return plan.features.includes("Tudo do Essencial") && essentialFeatures.includes(feature);
}

export function AdminPage() {
  const admin = useSaasAdmin();
  const { user } = useAuth();
  const { toast } = useToast();
  const [tab, setTab] = useState<AdminTab>("overview");
  const [materialOpen, setMaterialOpen] = useState(false);
  const [editingPlan, setEditingPlan] = useState<SaasPlan | null>(null);
  const active = admin.members.filter((member) => member.status === "active").length;
  const overdue = admin.members.filter((member) => member.status === "past_due").length;
  const mrr = admin.members.filter((member) => member.status === "active").reduce((sum, member) => sum + (admin.plans.find((plan) => plan.id === member.plan_id)?.monthly_price ?? 0), 0);

  if (admin.isLoading) return <div className="rounded-3xl border bg-card p-8 text-sm text-muted-foreground">Carregando controle do SaaS...</div>;
  if (!admin.isAdmin) return <div className="mx-auto max-w-lg rounded-3xl border bg-card p-8 text-center"><ShieldCheck className="mx-auto h-9 w-9 text-muted-foreground" /><h1 className="mt-4 text-2xl font-semibold">Área restrita</h1><p className="mt-2 text-sm text-muted-foreground">Somente o administrador principal pode acessar usuários, pagamentos e distribuição de materiais.</p></div>;

  const tabs: Array<{ id: AdminTab; label: string; description: string; icon: React.ElementType }> = [
    { id: "overview", label: "Visão geral", description: "Indicadores do SaaS", icon: BarChart3 },
    { id: "users", label: "Assinantes e acessos", description: "Planos e permissões", icon: Users },
    { id: "payments", label: "Cobrança", description: "Mensalidades e atrasos", icon: WalletCards },
    { id: "plans", label: "Produto e planos", description: "Preços e módulos", icon: Boxes },
    { id: "materials", label: "Conteúdo", description: "Distribuição nas agendas", icon: Megaphone },
    { id: "giveaways", label: "Sorteios", description: "Benefícios dos assinantes", icon: Gift },
    { id: "operations", label: "Operação", description: "Integrações e auditoria", icon: ServerCog },
    { id: "privacy", label: "Privacidade", description: "Pedidos dos titulares", icon: UserRoundX }
  ];

  return <div className="mx-auto w-full max-w-[1580px] space-y-5">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase text-primary">Controle central</p><h1 className="mt-1 text-3xl font-semibold">Super Admin</h1><p className="mt-1 text-sm text-muted-foreground">A operação da MV Broker separada da agenda dos assinantes.</p></div>{tab === "materials" && <Button onClick={() => setMaterialOpen(true)}><FileImage className="h-4 w-4" />Novo material</Button>}</header>
    <div className="grid gap-5 xl:grid-cols-[250px_minmax(0,1fr)]">
      <aside className="h-fit rounded-2xl border bg-card p-2 xl:sticky xl:top-24"><p className="px-3 pb-2 pt-2 text-[10px] font-bold uppercase tracking-[0.14em] text-muted-foreground">Controle do SaaS</p><nav className="grid gap-1">{tabs.map((item) => <button key={item.id} type="button" onClick={() => setTab(item.id)} className={cn("flex min-h-14 items-center gap-3 rounded-xl px-3 text-left transition hover:bg-muted/60", tab === item.id && "bg-foreground text-background shadow-sm")}><span className={cn("grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-muted text-muted-foreground", tab === item.id && "bg-primary/15 text-primary")}><item.icon className="h-4 w-4" /></span><span><span className="block text-sm font-semibold">{item.label}</span><span className={cn("block text-[10px] text-muted-foreground", tab === item.id && "text-background/55")}>{item.description}</span></span></button>)}</nav></aside>
      <div className="min-w-0 space-y-4">
        {tab === "overview" && <OverviewPanel active={active} total={admin.members.length} overdue={overdue} mrr={mrr} materials={admin.materials.filter((item) => item.published).length} members={admin.members} plans={admin.plans} payments={admin.payments} onNavigate={setTab} />}
        {tab === "users" && <SubscribersPanel members={admin.members} plans={admin.plans} payments={admin.payments} requests={admin.billingRequests} onUpdate={async (member, input) => { await admin.updateMember.mutateAsync({ id: member.id, input }); toast({ title: `Acesso de ${member.name} atualizado.` }); }} />}
        {tab === "materials" && <MaterialsPanel materials={admin.materials} onToggle={async (id, published) => { await admin.toggleMaterial.mutateAsync({ id, published }); toast({ title: published ? "Material publicado nas agendas." : "Material retirado das agendas." }); }} />}
        {tab === "payments" && <PaymentsPanel payments={admin.payments} requests={admin.billingRequests} onStatus={async (id, status) => { await admin.updatePayment.mutateAsync({ id, status }); toast({ title: "Status da cobrança atualizado." }); }} onRequestStatus={async (id, status) => { await admin.updateBillingRequest.mutateAsync({ id, status }); toast({ title: "Solicitação de assinatura atualizada." }); }} />}
        {tab === "plans" && <PlansPanel plans={admin.plans} onEdit={setEditingPlan} />}
        {tab === "giveaways" && <GiveawayPanel members={admin.members} plans={admin.plans} history={admin.giveaways} saving={admin.createGiveaway.isPending} onSave={async (draw) => { await admin.createGiveaway.mutateAsync(draw); }} />}
        {tab === "operations" && <OperationsPanel members={admin.members} logs={admin.auditLogs} />}
        {tab === "privacy" && <PrivacyPanel requests={admin.deletionRequests} processing={admin.processDeletionRequest.isPending} onStatus={async (id, status) => { await admin.updateDeletionRequest.mutateAsync({ id, status }); toast({ title: "Solicitação de privacidade atualizada." }); }} onDelete={async (id) => { await admin.processDeletionRequest.mutateAsync(id); toast({ title: "Conta e dados vinculados foram excluídos." }); }} />}
      </div>
    </div>
    <MaterialDialog open={materialOpen} pending={admin.createMaterial.isPending || admin.uploadMaterial.isPending} onOpenChange={setMaterialOpen} onSubmit={async (input, file, coverFile) => {
      let next = input;
      if (file) {
        const uploaded = await admin.uploadMaterial.mutateAsync(file);
        next = { ...input, material_type: uploaded.materialType, external_url: uploaded.externalUrl, storage_path: uploaded.storagePath, thumbnail_url: uploaded.materialType === "image" ? uploaded.externalUrl : input.thumbnail_url };
      }
      if (coverFile) {
        next = { ...next, thumbnail_url: await saveImageAsset(coverFile, user!.id, "materials") };
      }
      await admin.createMaterial.mutateAsync(next);
      setMaterialOpen(false);
      toast({ title: next.published ? "Material publicado para os assinantes." : "Material salvo como rascunho." });
    }} />
    <PlanDialog plan={editingPlan} pending={admin.updatePlan.isPending} onOpenChange={(open) => !open && setEditingPlan(null)} onSubmit={async (id, input) => { await admin.updatePlan.mutateAsync({ id, input }); setEditingPlan(null); toast({ title: "Plano atualizado." }); }} />
  </div>;
}

function OverviewPanel({ active, total, overdue, mrr, materials, members, plans, payments, onNavigate }: { active: number; total: number; overdue: number; mrr: number; materials: number; members: SaasMember[]; plans: SaasPlan[]; payments: SaasPayment[]; onNavigate: (tab: AdminTab) => void }) {
  const pendingRevenue = payments.filter((item) => ["pending", "overdue"].includes(item.status)).reduce((sum, item) => sum + item.amount, 0);
  return <div className="space-y-4"><section className="grid grid-cols-2 gap-3 xl:grid-cols-4"><AdminMetric label="Assinantes ativos" value={String(active)} detail={`${total} contas cadastradas`} /><AdminMetric label="Receita recorrente" value={brl.format(mrr)} detail="MRR estimado pelos planos" /><AdminMetric label="Pagamento atrasado" value={String(overdue)} detail={`${brl.format(pendingRevenue)} a acompanhar`} attention={overdue > 0} /><AdminMetric label="Materiais publicados" value={String(materials)} detail="disponíveis nas agendas" /></section><section className="rounded-2xl border bg-card p-4 sm:p-5"><div><h2 className="font-semibold">Áreas de controle</h2><p className="text-xs text-muted-foreground">Entre direto no que precisa administrar.</p></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><AdminShortcut icon={Users} title="Assinantes e acessos" detail={`${active} ativos · ${overdue} exigem atenção`} onClick={() => onNavigate("users")} /><AdminShortcut icon={WalletCards} title="Cobrança do SaaS" detail={`${payments.length} lançamentos acompanhados`} onClick={() => onNavigate("payments")} /><AdminShortcut icon={CreditCard} title="Planos e módulos" detail={`${plans.filter((item) => item.active).length} planos comerciais ativos`} onClick={() => onNavigate("plans")} /><AdminShortcut icon={Library} title="Conteúdo dos assinantes" detail={`${materials} materiais publicados`} onClick={() => onNavigate("materials")} /><AdminShortcut icon={Gift} title="Sorteio dos assinantes" detail={`${active} corretores aptos nesta rodada`} onClick={() => onNavigate("giveaways")} /><AdminShortcut icon={ServerCog} title="Operação do sistema" detail="Integrações e histórico administrativo" onClick={() => onNavigate("operations")} /></div></section><section className="grid gap-3 lg:grid-cols-2"><div className="rounded-2xl border bg-card p-5"><p className="text-xs font-bold uppercase text-muted-foreground">Distribuição por plano</p><div className="mt-4 space-y-3">{plans.map((plan) => { const count = members.filter((member) => member.plan_id === plan.id).length; const percent = total ? Math.round((count / total) * 100) : 0; return <div key={plan.id}><div className="flex justify-between text-xs"><span className="font-semibold">{plan.name}</span><span className="text-muted-foreground">{count} assinantes</span></div><div className="mt-2 h-1.5 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${percent}%` }} /></div></div>; })}</div></div><div className="rounded-2xl border bg-foreground p-5 text-background"><p className="text-xs font-bold uppercase text-primary">Saúde da operação</p><p className="mt-3 text-2xl font-semibold">{total ? Math.round((active / total) * 100) : 0}% da base ativa</p><p className="mt-2 text-sm leading-6 text-background/55">Acompanhe inadimplência, vencimentos e distribuição de módulos sem misturar com o financeiro pessoal dos corretores.</p></div></section></div>;
}

function AdminShortcut({ icon: Icon, title, detail, onClick }: { icon: React.ElementType; title: string; detail: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="flex min-h-20 items-center gap-3 rounded-xl border bg-background p-3 text-left transition hover:border-primary/40 hover:bg-primary/[0.03]"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="h-5 w-5" /></span><span><span className="block text-sm font-semibold">{title}</span><span className="mt-0.5 block text-[11px] text-muted-foreground">{detail}</span></span></button>; }

function AdminMetric({ label, value, detail, attention }: { label: string; value: string; detail: string; attention?: boolean }) { return <article className="rounded-2xl border bg-card p-4 shadow-sm"><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className={cn("mt-3 text-2xl font-semibold tabular-nums", attention && "text-destructive")}>{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{detail}</p></article>; }

function MaterialsPanel({ materials, onToggle }: { materials: SaasMaterial[]; onToggle: (id: string, published: boolean) => Promise<void> }) { return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{materials.map((material) => <article key={material.id} className="overflow-hidden rounded-2xl border bg-card"><div className="aspect-[16/7] bg-muted">{material.thumbnail_url ? <img src={material.thumbnail_url} alt="" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center"><FileImage className="h-8 w-8 text-muted-foreground" /></div>}</div><div className="p-4"><div className="flex items-start justify-between gap-3"><div><span className="text-[10px] font-semibold uppercase text-primary">{material.category}</span><h3 className="mt-1 font-semibold">{material.title}</h3></div><MoreHorizontal className="h-4 w-4 text-muted-foreground" /></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-muted-foreground">{material.description}</p><div className="mt-4 flex items-center justify-between"><span className={cn("rounded-full px-2.5 py-1 text-[10px] font-semibold", material.published ? "bg-emerald-500/10 text-emerald-600" : "bg-muted text-muted-foreground")}>{material.published ? "Publicado" : "Rascunho"}</span><Button size="sm" variant="outline" onClick={() => void onToggle(material.id, !material.published)}>{material.published ? "Retirar" : "Publicar"}</Button></div></div></article>)}</div>; }

function PaymentsPanel({ payments, requests, onStatus, onRequestStatus }: { payments: SaasPayment[]; requests: SaasBillingRequest[]; onStatus: (id: string, status: SaasPayment["status"]) => Promise<void>; onRequestStatus: (id: string, status: SaasBillingRequest["status"]) => Promise<void> }) { return <div className="space-y-4">{requests.length > 0 && <section className="rounded-2xl border bg-card"><div className="border-b p-4"><h2 className="font-semibold">Solicitações dos assinantes</h2><p className="text-xs text-muted-foreground">Trocas, ativações e cancelamentos aguardando processamento.</p></div><div className="divide-y">{requests.map((request) => <div key={request.id} className="grid gap-2 p-4 sm:grid-cols-[minmax(0,1fr)_130px_120px_150px] sm:items-center"><div><p className="text-sm font-semibold">{request.member_name}</p><p className="text-xs text-muted-foreground">{request.action.replace("_", " ")} · {request.billing_cycle === "annual" ? "anual" : "mensal"}</p></div><p className="text-xs text-muted-foreground">{new Date(request.created_at).toLocaleString("pt-BR")}</p><StatusBadge status={request.status} /><select value={request.status} onChange={(event) => void onRequestStatus(request.id, event.target.value as SaasBillingRequest["status"])} className="h-10 rounded-xl border bg-background px-3 text-xs font-semibold"><option value="pending">Pendente</option><option value="processing">Processando</option><option value="completed">Concluída</option><option value="failed">Falhou</option><option value="canceled">Cancelada</option></select></div>)}</div></section>}<section className="rounded-2xl border bg-card"><div className="border-b p-4"><h2 className="font-semibold">Cobranças e pagamentos</h2><p className="text-xs text-muted-foreground">Visão operacional das mensalidades.</p></div><div className="divide-y">{payments.map((payment) => <div key={payment.id} className="grid gap-2 p-4 sm:grid-cols-[minmax(0,1fr)_120px_130px_120px_150px] sm:items-center"><div><p className="text-sm font-semibold">{payment.member_name}</p><p className="text-xs text-muted-foreground">{payment.payment_method}</p></div><p className="text-sm font-semibold tabular-nums">{brl.format(payment.amount)}</p><p className="text-xs text-muted-foreground">Vence {formatDate(payment.due_date)}</p><StatusBadge status={payment.status} /><select value={payment.status} onChange={(event) => void onStatus(payment.id, event.target.value as SaasPayment["status"])} className="h-10 rounded-xl border bg-background px-3 text-xs font-semibold"><option value="pending">Pendente</option><option value="paid">Pago</option><option value="overdue">Atrasado</option><option value="refunded">Estornado</option><option value="canceled">Cancelado</option></select></div>)}</div></section></div>; }

function PrivacyPanel({ requests, processing, onStatus, onDelete }: { requests: SaasDeletionRequest[]; processing: boolean; onStatus: (id: string, status: SaasDeletionRequest["status"]) => Promise<void>; onDelete: (id: string) => Promise<void> }) { return <section className="rounded-2xl border bg-card"><div className="border-b p-4"><h2 className="font-semibold">Solicitações de privacidade</h2><p className="text-xs text-muted-foreground">A conclusão exclui a conta no Auth e os dados vinculados, com registro técnico de auditoria.</p></div>{requests.length ? <div className="divide-y">{requests.map((request) => <div key={request.id} className="grid gap-3 p-4 lg:grid-cols-[minmax(0,1fr)_130px_150px_170px] lg:items-center"><div><p className="text-sm font-semibold">{request.email || "E-mail não informado"}</p><p className="text-xs text-muted-foreground">Solicitado em {new Date(request.requested_at).toLocaleString("pt-BR")}</p></div><StatusBadge status={request.status} /><select value={request.status} onChange={(event) => void onStatus(request.id, event.target.value as SaasDeletionRequest["status"])} className="h-10 rounded-xl border bg-background px-3 text-xs font-semibold" disabled={request.status === "completed"}><option value="requested">Solicitado</option><option value="in_review">Em análise</option><option value="canceled">Cancelado</option></select><Button variant="destructive" disabled={processing || !["requested", "in_review"].includes(request.status)} onClick={() => { if (window.confirm("Excluir definitivamente esta conta e todos os dados vinculados? Esta ação não pode ser desfeita.")) void onDelete(request.id); }}><UserRoundX className="h-4 w-4" />Excluir conta</Button></div>)}</div> : <div className="p-10 text-center text-sm text-muted-foreground">Nenhuma solicitação de exclusão pendente.</div>}</section>; }

function PlansPanel({ plans, onEdit }: { plans: SaasPlan[]; onEdit: (plan: SaasPlan) => void }) { return <div className="grid gap-4 lg:grid-cols-3">{plans.map((plan) => <article key={plan.id} className="rounded-2xl border bg-card p-5"><div className="flex items-center justify-between"><p className="text-xs font-semibold uppercase text-primary">{plan.name}</p><span className={cn("rounded-full px-2 py-1 text-[10px] font-semibold", plan.active ? "bg-emerald-500/10 text-emerald-600" : "bg-muted text-muted-foreground")}>{plan.active ? "Ativo" : "Inativo"}</span></div><p className="mt-4 text-3xl font-semibold">{brl.format(plan.monthly_price)}<span className="text-xs font-medium text-muted-foreground">/mês</span></p><p className="mt-2 text-sm text-muted-foreground">{plan.description}</p><div className="mt-5 space-y-2">{planFeatures.filter((feature) => hasPlanFeature(plan, feature)).map((feature) => <p key={feature} className="flex items-center gap-2 text-xs"><span className="grid h-5 w-5 place-items-center rounded-full bg-emerald-500/10 text-emerald-600">✓</span>{feature}</p>)}</div><Button variant="outline" className="mt-5 w-full" onClick={() => onEdit(plan)}>Editar plano</Button></article>)}</div>; }

function MaterialDialog({ open, pending, onOpenChange, onSubmit }: { open: boolean; pending: boolean; onOpenChange: (open: boolean) => void; onSubmit: (input: MaterialInput, file?: File, coverFile?: File) => Promise<void> }) {
  const [source, setSource] = useState<"upload" | "link">("upload");
  const [coverFile, setCoverFile] = useState<File | null>(null);
  const { toast } = useToast();
  useEffect(() => { if (open) setCoverFile(null); }, [open]);
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    const fileValue = form.get("file");
    const file = source === "upload" && fileValue instanceof File && fileValue.size > 0 ? fileValue : undefined;
    const externalUrl = source === "link" ? String(form.get("externalUrl") ?? "") : "";
    if (!file && !externalUrl) return;
    try {
      await onSubmit({ title: String(form.get("title")), description: String(form.get("description") ?? ""), category: String(form.get("category")), material_type: String(form.get("materialType")) as MaterialInput["material_type"], thumbnail_url: "", external_url: externalUrl, storage_path: null, target_plan_ids: [], published: form.get("published") === "on" }, file, coverFile ?? undefined);
      setCoverFile(null);
    } catch (error) { toast({ title: error instanceof Error ? error.message : "Não foi possível enviar o material.", variant: "error" }); }
  }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Distribuir novo material</DialogTitle><DialogDescription>Envie uma imagem, vídeo ou PDF, ou compartilhe uma pasta e um link com os assinantes.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><div className="grid grid-cols-2 gap-2 rounded-2xl bg-muted p-1.5"><button type="button" onClick={() => setSource("upload")} className={cn("flex min-h-10 items-center justify-center gap-2 rounded-xl text-sm font-semibold", source === "upload" && "bg-background shadow-sm")}><Upload className="h-4 w-4" />Enviar arquivo</button><button type="button" onClick={() => setSource("link")} className={cn("flex min-h-10 items-center justify-center gap-2 rounded-xl text-sm font-semibold", source === "link" && "bg-background shadow-sm")}><Link2 className="h-4 w-4" />Usar link</button></div><div><Label htmlFor="material-title">Nome do material</Label><Input id="material-title" name="title" className="mt-2" required /></div><div className="grid gap-4 sm:grid-cols-2"><div><Label htmlFor="material-category">Categoria</Label><Input id="material-category" name="category" className="mt-2" placeholder="Marketing" required /></div><div><Label htmlFor="material-type">Tipo</Label><select id="material-type" name="materialType" className="mt-2 h-12 w-full rounded-2xl border bg-background px-4 text-sm" disabled={source === "upload"}><option value="image">Imagem</option><option value="video">Vídeo</option><option value="pdf">PDF</option><option value="drive">Drive</option><option value="link">Link</option></select></div></div>{source === "upload" ? <div><Label htmlFor="material-file">Arquivo</Label><Input id="material-file" name="file" type="file" accept="image/jpeg,image/png,image/webp,video/mp4,video/quicktime,application/pdf" className="mt-2 cursor-pointer file:mr-3 file:border-0 file:bg-transparent file:text-sm file:font-semibold" required /><p className="mt-1 text-xs text-muted-foreground">JPG, PNG, WebP e PDF até 20 MB. MP4 e MOV até 200 MB.</p></div> : <div><Label htmlFor="material-url">Link do arquivo ou pasta</Label><Input id="material-url" name="externalUrl" type="url" className="mt-2" required /></div>}<ImageUploadField label="Foto de capa (opcional)" file={coverFile} onFileChange={setCoverFile} onClear={() => setCoverFile(null)} /><div><Label htmlFor="material-description">Descrição</Label><Textarea id="material-description" name="description" className="mt-2" /></div><label className="flex items-center gap-3 rounded-xl border p-3 text-sm font-semibold"><input type="checkbox" name="published" defaultChecked className="h-4 w-4 accent-primary" />Publicar agora para os assinantes</label><Button disabled={pending}>{pending ? "Enviando..." : "Salvar material"}</Button></form></DialogContent></Dialog>;
}

function PlanDialog({ plan, pending, onOpenChange, onSubmit }: { plan: SaasPlan | null; pending: boolean; onOpenChange: (open: boolean) => void; onSubmit: (id: string, input: Partial<SaasPlan>) => Promise<void> }) {
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (!plan) return; const form = new FormData(event.currentTarget); await onSubmit(plan.id, { name: String(form.get("name")), description: String(form.get("description") ?? ""), monthly_price: Number(form.get("monthlyPrice")), annual_price: Number(form.get("annualPrice")), features: form.getAll("features").map(String), active: form.get("active") === "on" }); }
  return <Dialog open={Boolean(plan)} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle>Editar plano</DialogTitle><DialogDescription>Defina preço, disponibilidade e quais módulos fazem parte deste plano.</DialogDescription></DialogHeader>{plan && <form key={plan.id} onSubmit={submit} className="grid gap-4"><div><Label htmlFor="plan-name">Nome</Label><Input id="plan-name" name="name" defaultValue={plan.name} className="mt-2" required /></div><div className="grid grid-cols-2 gap-3"><div><Label htmlFor="plan-monthly">Mensal</Label><Input id="plan-monthly" name="monthlyPrice" type="number" min="0" step="0.01" defaultValue={plan.monthly_price} className="mt-2" required /></div><div><Label htmlFor="plan-annual">Anual</Label><Input id="plan-annual" name="annualPrice" type="number" min="0" step="0.01" defaultValue={plan.annual_price} className="mt-2" required /></div></div><div><Label htmlFor="plan-description">Descrição</Label><Textarea id="plan-description" name="description" defaultValue={plan.description} className="mt-2" /></div><fieldset><legend className="text-sm font-semibold">Módulos liberados</legend><div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-3">{planFeatures.map((feature) => <label key={feature} className="flex min-h-11 items-center gap-2 rounded-xl border bg-background px-3 text-xs font-medium"><input type="checkbox" name="features" value={feature} defaultChecked={hasPlanFeature(plan, feature)} className="h-4 w-4 accent-primary" />{feature}</label>)}</div></fieldset><label className="flex items-center gap-3 rounded-xl border p-3 text-sm font-semibold"><input type="checkbox" name="active" defaultChecked={plan.active} className="h-4 w-4 accent-primary" />Plano disponível para novas assinaturas</label><Button disabled={pending}>{pending ? "Salvando..." : "Salvar plano"}</Button></form>}</DialogContent></Dialog>;
}

function StatusBadge({ status }: { status: string }) { const label: Record<string, string> = { active: "Ativo", trialing: "Em teste", past_due: "Inadimplente", suspended: "Suspenso", canceled: "Cancelado", paid: "Pago", pending: "Pendente", processing: "Processando", failed: "Falhou", overdue: "Atrasado", refunded: "Estornado", requested: "Solicitado", in_review: "Em análise", completed: "Concluído" }; return <span className={cn("w-fit rounded-full px-2.5 py-1 text-[10px] font-semibold", ["active", "paid", "completed"].includes(status) ? "bg-emerald-500/10 text-emerald-600" : ["past_due", "overdue", "suspended", "failed"].includes(status) ? "bg-destructive/10 text-destructive" : "bg-muted text-muted-foreground")}>{label[status] ?? status}</span>; }
function formatDate(value: string) { if (!value) return "—"; return new Date(`${value.slice(0, 10)}T12:00:00`).toLocaleDateString("pt-BR"); }
