import type { Building } from "@/types/database";

export const verifiedBuildingEnrichment: Record<string, Partial<Building>> = {
  "d09cbbb7-7303-587e-9041-ec80ab223d83": {
    city: "Capão da Canoa",
    state: "RS",
    elevators: 2,
    amenities: ["Áreas sociais mobiliadas", "Espaço gourmet", "Espaço kids", "Gás central", "Hall decorado", "Piscina aquecida", "Playground", "Salão de festas", "Zeladoria"],
    description: "Empreendimento residencial de padrão elevado no bairro Navegantes, com rooftop, piscina aquecida, espaços de convivência e sacadas voltadas para a paisagem urbana e marítima.",
    sourceUrl: "https://www.imobiliariafb.com.br/condominio/2079",
    sourceTitle: "Mirage · catálogo imobiliário público",
    sourceCheckedAt: "2026-09-30",
    verificationStatus: "web",
    notes: "Dois elevadores e infraestrutura confirmados em catálogo imobiliário público. Construtora, ano, número de andares e total de unidades ainda precisam ser confirmados."
  },
  "20183cc1-5d01-5f76-9ab5-c37d671f8186": {
    city: "Capão da Canoa",
    state: "RS",
    builder: "Nazale Incorporadora e Construtora",
    developer: "Nazale Incorporadora e Construtora",
    constructionYear: 2011,
    deliveryYear: 2011,
    elevators: 2,
    bedroomsMin: 2,
    bedroomsMax: 4,
    amenities: ["Academia", "Acessibilidade", "Churrasqueira", "Hall decorado", "Piscina", "Portaria eletrônica", "Zeladoria"],
    description: "Edifício residencial próximo ao mar e à praça de lazer, com apartamentos de 2 a 4 dormitórios, piscina, academia e estrutura de convivência.",
    sourceUrl: "https://www.ilitoral.com.br/condominio/ver/le-grand-park-capao-da-canoa%2C426",
    sourceTitle: "Le Grand Park · catálogo imobiliário público",
    sourceCheckedAt: "2026-09-30",
    verificationStatus: "web",
    notes: "Construtora, conclusão em 2011, tipologias, dois elevadores e infraestrutura constam em catálogo imobiliário público. Total de unidades e andares ainda não foram confirmados."
  },
  "4524831a-2ede-58a9-8d4f-e10a1a919f53": {
    city: "Capão da Canoa",
    state: "RS",
    postalCode: "95555-000",
    coverUrl: "/buildings/via-del-mare.jpg",
    coverSourceUrl: "https://www.omelhordapraia.com.br/imovel/664-apartamento-de-3-dormitorios-sacada-de-frente-predio-com-infraestrutura-apenas-3-quadras-da-praia",
    coverSourceTitle: "Fachada · O Melhor da Praia",
    builder: "Nazale Incorporadora e Construtora",
    developer: "Nazale Incorporadora e Construtora",
    elevators: 2,
    bedroomsMin: 1,
    bedroomsMax: 3,
    privateAreaMin: 43.45,
    privateAreaMax: 119.48,
    amenities: [
      "Academia",
      "Brinquedoteca",
      "Churrasqueira",
      "Piscina aquecida",
      "Playground",
      "Sala de cinema",
      "Sala de jogos",
      "Salão de festas",
      "Varanda"
    ],
    description: "Empreendimento residencial no bairro Navegantes, a três quadras do mar, com apartamentos de 1, 2 e 3 dormitórios e infraestrutura de lazer.",
    websiteUrl: "https://nazale.com.br/via-del-mare/",
    sourceUrl: "https://nazale.com.br/via-del-mare/",
    sourceTitle: "Via Del Mare · Nazale",
    sourceCheckedAt: "2026-09-28",
    verificationStatus: "verificado",
    notes: "Construtora, tipologias, áreas e lazer confirmados na página oficial. Dois elevadores confirmados em anúncio imobiliário local. Ano de construção e total de unidades ainda não foram confirmados."
  },
  "c22a926e-f2cd-5503-855d-4263e5f616b9": {
    city: "Capão da Canoa",
    state: "RS",
    builder: "Nazale Incorporadora e Construtora",
    developer: "Nazale Incorporadora e Construtora",
    deliveryYear: 2013,
    elevators: 2,
    bedroomsMin: 1,
    bedroomsMax: 4,
    privateAreaMin: 75.84,
    privateAreaMax: 257.53,
    amenities: ["Academia", "Bicicletário", "Churrasqueira", "Espaço gourmet", "Gás central", "Piscina aquecida", "Salão de festas"],
    description: "Empreendimento residencial de frente para o mar, no bairro Navegantes, com apartamentos de 1, 2 e 4 dormitórios e infraestrutura de lazer.",
    websiteUrl: "https://nazale.com.br/residencial-deauville/",
    sourceUrl: "https://nazale.com.br/residencial-deauville/",
    sourceTitle: "Residencial Deauville · Nazale",
    sourceCheckedAt: "2026-09-30",
    verificationStatus: "web",
    notes: "Construtora, tipologias, áreas e lazer confirmados no site oficial. Entrega e dois elevadores constam em catálogo imobiliário público. O logradouro publicado diverge da base original e deve ser confirmado antes de substituir o endereço."
  },
  "672302dd-8347-56d2-b81f-71468445823b": {
    city: "Capão da Canoa",
    state: "RS",
    builder: "Marina Park Construtora",
    developer: "Marina Park Construtora",
    constructionYear: 2012,
    deliveryYear: 2012,
    elevators: 2,
    bedroomsMin: 2,
    bedroomsMax: 4,
    amenities: ["Academia", "Acessibilidade", "Churrasqueira", "Espaço gourmet", "Gás central", "Piscina", "Portaria eletrônica", "Sala de jogos", "Salão de festas", "Zeladoria"],
    description: "Edifício de alto padrão no bairro Navegantes, próximo ao mar, com apartamentos de 2 a 4 dormitórios e áreas de convivência.",
    sourceUrl: "https://www.ilitoral.com.br/condominio/ver/dubai-capao-da-canoa%2C220",
    sourceTitle: "Dubai · catálogo imobiliário público",
    sourceCheckedAt: "2026-09-30",
    verificationStatus: "web",
    notes: "Ficha preenchida a partir de catálogo imobiliário público. Confirmar matrícula, total de unidades e dados condominiais diretamente com a administradora ou construtora."
  },
  "ded5fd5a-a6f5-5c4c-9a00-15cfe980d78e": {
    city: "Capão da Canoa",
    state: "RS",
    elevators: 2,
    amenities: ["Água quente", "Churrasqueira", "Espaço gourmet", "Hall decorado"],
    description: "Edifício residencial no bairro Navegantes. Anúncios públicos registram hall decorado, dois elevadores e apartamentos com churrasqueira.",
    sourceUrl: "https://www.upimoveis.imb.br/imovel/1294569/edificio-pacific",
    sourceTitle: "Edifício Pacific · anúncio imobiliário público",
    sourceCheckedAt: "2026-09-30",
    verificationStatus: "web",
    notes: "A fonte consultada descreve uma unidade específica; metragem, dormitórios e vagas não foram generalizados para todo o edifício."
  },
  "f7a3976b-9dae-52e7-b146-f77061653675": {
    city: "Capão da Canoa",
    state: "RS",
    floors: 12,
    totalUnits: 45,
    unitsPerFloor: 5,
    elevators: 2,
    bedroomsMin: 2,
    amenities: ["Acessibilidade", "Churrasqueira", "Espaço gourmet", "Gás central", "Gerador", "Hall decorado", "Piscina aquecida", "Portaria eletrônica", "Sala de jogos", "Salão de festas", "Zeladoria"],
    description: "Edifício residencial na Avenida Central, com 45 apartamentos, áreas sociais equipadas e infraestrutura de lazer com piscina aquecida.",
    sourceUrl: "https://imobiliariafb.com.br/condominio/758",
    sourceTitle: "Acqua di Firenze · catálogo imobiliário público",
    sourceCheckedAt: "2026-09-30",
    verificationStatus: "web",
    notes: "Andares, unidades, unidades por andar, elevadores e lazer confirmados em catálogo imobiliário público. Área e vaga publicadas se referem a uma unidade e não foram generalizadas."
  },
  "857d8ba7-e14a-5516-af05-d00faabd0e21": {
    city: "Capão da Canoa",
    state: "RS",
    postalCode: "95555-000",
    towers: 1,
    elevators: 2,
    bedroomsMin: 1,
    bedroomsMax: 3,
    amenities: ["Churrasqueira", "Espaço gourmet", "Hall decorado", "Jardim", "Portaria eletrônica", "Salão de festas", "Zeladoria"],
    description: "Edifício residencial na Zona Nova, a poucos passos do mar e de praças, com apartamentos de 1 a 3 dormitórios e salão de festas equipado.",
    sourceUrl: "https://www.proencaimoveis.com.br/condominio/859",
    sourceTitle: "Majestic Tower · catálogo imobiliário público",
    sourceCheckedAt: "2026-09-30",
    verificationStatus: "web",
    notes: "Tipologias, dois elevadores e infraestrutura confirmados em catálogo imobiliário público. Uma torre e endereço foram cruzados com outro catálogo público. Ano e total de unidades ainda não confirmados."
  },
  "c4b604f0-1384-5063-b28a-98726ade2462": {
    city: "Capão da Canoa",
    state: "RS",
    postalCode: "95555-000",
    floors: 13,
    elevators: 2,
    bedroomsMin: 2,
    bedroomsMax: 4,
    privateAreaMin: 85,
    privateAreaMax: 209,
    amenities: ["Acessibilidade", "Churrasqueira", "Gás central", "Hall decorado", "Portaria 24h", "Salão de festas", "Zeladoria"],
    description: "Edifício residencial de frente para o mar no bairro Navegantes, com 13 andares, apartamentos de 2 a 4 dormitórios e salão de festas.",
    sourceUrl: "https://www.imobiliariafb.com.br/condominio/886",
    sourceTitle: "Dunnas Park · catálogo imobiliário público",
    sourceCheckedAt: "2026-09-30",
    verificationStatus: "web",
    notes: "Andares, infraestrutura e tipologias foram cruzados em catálogos imobiliários públicos. As áreas representam a faixa observada nos anúncios disponíveis; construtora e total de unidades ainda precisam ser confirmados."
  },
  "91ba36a6-d45b-54c0-a298-ab174b6b0c09": {
    city: "Capão da Canoa",
    state: "RS",
    floors: 12,
    unitsPerFloor: 2,
    elevators: 2,
    bedroomsMin: 2,
    bedroomsMax: 3,
    amenities: ["Água quente", "Churrasqueira", "Gás central", "Hall decorado", "Portaria 24h", "Vista para o mar"],
    description: "Edifício beira-mar no bairro Navegantes, com dois apartamentos por andar, opções de 2 e 3 dormitórios e vista para o mar e o calçadão.",
    sourceUrl: "https://www.imobiliariafb.com.br/condominio/901",
    sourceTitle: "Ferdinando Martinello · catálogo imobiliário público",
    sourceCheckedAt: "2026-09-30",
    verificationStatus: "web",
    notes: "Doze andares, duas unidades por andar, dois elevadores, tipologias e infraestrutura confirmados em catálogo imobiliário público. Construtora e ano ainda não confirmados."
  },
  "04fbaeea-f216-5a66-8090-962da84260a1": {
    city: "Capão da Canoa",
    state: "RS",
    floors: 15,
    totalUnits: 50,
    unitsPerFloor: 5,
    elevators: 2,
    bedroomsMin: 2,
    bedroomsMax: 4,
    amenities: ["Academia", "Churrasqueira", "Coworking", "Espaço gourmet", "Espaço kids", "Hall decorado", "Jacuzzi", "Piscina aquecida", "Rooftop", "Sala de jogos", "Salão de festas", "Sauna"],
    description: "Empreendimento residencial de alto padrão com 50 apartamentos, rooftop e aproximadamente 660 m² de lazer, incluindo piscinas aquecidas, sauna, academia e espaços de convivência.",
    sourceUrl: "https://www.imobiliariafb.com.br/condominio/2196",
    sourceTitle: "Four Seasons Residence · catálogo imobiliário público",
    sourceCheckedAt: "2026-09-30",
    verificationStatus: "web",
    notes: "Andares, unidades, unidades por andar, elevadores, tipologias e infraestrutura confirmados em catálogo imobiliário público. Construtora, ano e áreas privativas ainda precisam ser confirmados."
  }
};

export function enrichBuilding(building: Building): Building {
  const defined = Object.fromEntries(Object.entries(building).filter(([, value]) => value !== undefined));
  return { city: "Capão da Canoa", state: "RS", verificationStatus: "pendente", amenities: [], ...defined, ...verifiedBuildingEnrichment[building.id] } as Building;
}
