import { useMemo, useState } from "react";
import { Download, ExternalLink, FileArchive, FileImage, FileText, Folder, Grid2X2, Link2, List, Plus, Search, Star, Trash2, UploadCloud, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useToast } from "@/components/ui/toast";
import { useClients } from "@/features/clients/use-clients";
import { cn } from "@/lib/utils";
import type { BrokerFile, BrokerFileType, Client } from "@/types/database";
import { formatBytes, useBrokerFiles } from "./use-broker-files";

type ViewMode = "cards" | "list";
type SortMode = "recent" | "oldest" | "name";
const categories = ["Clientes", "Contratos", "Documentação", "Imóveis", "Marketing", "Propostas", "Comprovantes", "Geral"];
const defaultFolders = ["Geral", "Clientes", "Imóveis", "Contratos", "Marketing", "Financeiro"];

export function MyFilesPage() {
  const files = useBrokerFiles();
  const { clients } = useClients();
  const { toast } = useToast();
  const [open, setOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [type, setType] = useState<BrokerFileType | "all">("all");
  const [category, setCategory] = useState("all");
  const [folder, setFolder] = useState("all");
  const [clientId, setClientId] = useState("all");
  const [favoriteOnly, setFavoriteOnly] = useState(false);
  const [sort, setSort] = useState<SortMode>("recent");
  const [view, setView] = useState<ViewMode>("cards");

  const usedCategories = Array.from(new Set([...categories, ...files.files.map((file) => file.category)])).sort();
  const usedFolders = Array.from(new Set([...defaultFolders, ...files.files.map((file) => file.folder || "Geral")])).sort();
  const folderCounts = useMemo(() => usedFolders.map((name) => ({ name, count: files.files.filter((file) => (file.folder || "Geral") === name).length })).filter((item) => item.count), [files.files, usedFolders]);
  const visible = useMemo(() => files.files.filter((file) => {
    const term = search.trim().toLocaleLowerCase("pt-BR");
    const searchable = `${file.title} ${file.category} ${file.folder || "Geral"} ${file.client_name ?? ""} ${(file.tags ?? []).join(" ")}`.toLocaleLowerCase("pt-BR");
    return (!term || searchable.includes(term)) && (type === "all" || file.file_type === type) && (category === "all" || file.category === category) && (folder === "all" || (file.folder || "Geral") === folder) && (clientId === "all" || (clientId === "general" ? !file.client_id : clientId === "linked" ? Boolean(file.client_id) : file.client_id === clientId)) && (!favoriteOnly || file.is_favorite);
  }).sort((a, b) => sort === "name" ? a.title.localeCompare(b.title, "pt-BR") : sort === "oldest" ? a.created_at.localeCompare(b.created_at) : b.created_at.localeCompare(a.created_at)), [category, clientId, favoriteOnly, files.files, folder, search, sort, type]);

  async function remove(file: BrokerFile) { try { await files.remove.mutateAsync(file); toast({ title: "Arquivo removido." }); } catch { toast({ title: "Não foi possível remover o arquivo.", variant: "error" }); } }
  async function toggleFavorite(file: BrokerFile) { try { await files.updateMeta.mutateAsync({ asset: file, changes: { is_favorite: !file.is_favorite } }); toast({ title: file.is_favorite ? "Removido dos favoritos." : "Adicionado aos favoritos." }); } catch { toast({ title: "Não foi possível atualizar o favorito.", variant: "error" }); } }
  function resetFilters() { setType("all"); setCategory("all"); setFolder("all"); setClientId("all"); setFavoriteOnly(false); }

  return <div className="mx-auto w-full max-w-[1580px] space-y-5 overflow-x-hidden">
    <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-semibold uppercase text-primary">Central documental</p><h1 className="mt-1 text-3xl font-semibold">Meus Arquivos</h1><p className="mt-1 text-sm text-muted-foreground">Sua biblioteca de fotos, PDFs e links, separada por pastas e clientes.</p></div><Button className="h-11 w-full sm:w-auto" onClick={() => setOpen(true)}><Plus className="h-4 w-4" />Novo arquivo</Button></header>

    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4">
      <Metric label="Todos" value={files.files.length} icon={FileArchive} active={!favoriteOnly && type === "all" && clientId === "all"} onClick={resetFilters} />
      <Metric label="Fotos" value={files.files.filter((item) => item.file_type === "image").length} icon={FileImage} active={type === "image"} onClick={() => { resetFilters(); setType("image"); }} />
      <Metric label="Favoritos" value={files.files.filter((item) => item.is_favorite).length} icon={Star} active={favoriteOnly} onClick={() => { resetFilters(); setFavoriteOnly(true); }} />
      <Metric label="Com clientes" value={files.files.filter((item) => item.client_id).length} icon={UserRound} active={clientId === "linked"} onClick={() => { resetFilters(); setClientId("linked"); }} />
    </section>

    {folderCounts.length > 0 && <section><div className="mb-2 flex items-center justify-between"><h2 className="text-sm font-semibold">Pastas</h2><span className="text-xs text-muted-foreground">{folderCounts.length} organizadas</span></div><div className="flex gap-2 overflow-x-auto pb-2">{folderCounts.map((item) => <button key={item.name} type="button" onClick={() => setFolder(folder === item.name ? "all" : item.name)} className={cn("flex min-w-[142px] items-center gap-3 rounded-2xl border bg-card p-3 text-left transition", folder === item.name && "border-primary bg-primary/5 ring-1 ring-primary/20")}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-muted text-primary"><Folder className="h-5 w-5" /></span><span className="min-w-0"><span className="block truncate text-sm font-semibold">{item.name}</span><span className="text-xs text-muted-foreground">{item.count} {item.count === 1 ? "item" : "itens"}</span></span></button>)}</div></section>}

    <section className="rounded-2xl border bg-card p-3"><div className="grid gap-2 md:grid-cols-2 xl:grid-cols-[minmax(240px,1fr)_145px_165px_165px_190px_150px_auto]">
      <div className="relative md:col-span-2 xl:col-span-1"><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(event) => setSearch(event.target.value)} className="pl-10" placeholder="Buscar arquivo, pasta, cliente ou etiqueta" /></div>
      <Filter value={type} onChange={(value) => setType(value as BrokerFileType | "all")} options={[["all","Todos os tipos"],["image","Fotos"],["pdf","PDFs"],["link","Links"]]} />
      <Filter value={folder} onChange={setFolder} options={[["all", "Todas as pastas"], ...usedFolders.map((item) => [item, item] as [string,string])]} />
      <Filter value={category} onChange={setCategory} options={[["all", "Categorias"], ...usedCategories.map((item) => [item, item] as [string,string])]} />
      <Filter value={clientId} onChange={setClientId} options={[["all", "Todos os clientes"], ["linked", "Com clientes"], ["general", "Sem cliente"], ...clients.map((client) => [client.id, client.name] as [string,string])]} />
      <Filter value={sort} onChange={(value) => setSort(value as SortMode)} options={[["recent", "Mais recentes"], ["oldest", "Mais antigos"], ["name", "Nome A–Z"]]} />
      <div className="grid min-h-12 grid-cols-2 rounded-xl border bg-muted/35 p-1"><ViewButton active={view === "cards"} icon={Grid2X2} label="Cards" onClick={() => setView("cards")} /><ViewButton active={view === "list"} icon={List} label="Lista" onClick={() => setView("list")} /></div>
    </div></section>

    <div className="flex items-center justify-between gap-3"><p className="text-sm text-muted-foreground"><strong className="text-foreground">{visible.length}</strong> resultado(s)</p>{(search || type !== "all" || category !== "all" || folder !== "all" || clientId !== "all" || favoriteOnly) && <Button variant="ghost" size="sm" onClick={() => { setSearch(""); resetFilters(); }}>Limpar filtros</Button>}</div>
    {files.isLoading ? <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{Array.from({length:6}).map((_,index)=><div key={index} className="h-48 animate-pulse rounded-2xl bg-muted" />)}</div> : visible.length ? <div className={cn(view === "cards" ? "grid gap-3 sm:grid-cols-2 xl:grid-cols-3" : "space-y-2")}>{visible.map((file) => <FileItem key={file.id} file={file} view={view} onFavorite={() => void toggleFavorite(file)} onRemove={() => void remove(file)} />)}</div> : <EmptyFiles onAdd={() => setOpen(true)} />}
    <FileCreateDialog open={open} onOpenChange={setOpen} clients={clients} folders={usedFolders} onUpload={files.upload.mutateAsync} onLink={files.addLink.mutateAsync} />
  </div>;
}

export function ClientFilesPanel({ client }: { client: Client }) {
  const files = useBrokerFiles(client.id);
  const { toast } = useToast();
  const [open, setOpen] = useState(false);
  async function remove(file: BrokerFile) { try { await files.remove.mutateAsync(file); toast({ title: "Arquivo removido." }); } catch { toast({ title: "Não foi possível remover o arquivo.", variant: "error" }); } }
  async function toggleFavorite(file: BrokerFile) { try { await files.updateMeta.mutateAsync({ asset: file, changes: { is_favorite: !file.is_favorite } }); } catch { toast({ title: "Não foi possível atualizar o favorito.", variant: "error" }); } }
  return <section className="rounded-xl border p-4"><div className="flex items-center justify-between gap-3"><div><div className="flex items-center gap-2"><FileArchive className="h-4 w-4 text-primary" /><h3 className="font-semibold">Arquivos do cliente</h3></div><p className="mt-1 text-xs text-muted-foreground">Documentos, fotos e links desta negociação.</p></div><Button size="sm" variant="outline" onClick={() => setOpen(true)}><Plus className="h-4 w-4" />Adicionar</Button></div>{files.files.length ? <div className="mt-4 space-y-2">{files.files.slice(0, 8).map((file) => <FileItem key={file.id} file={file} view="list" compact onFavorite={() => void toggleFavorite(file)} onRemove={() => void remove(file)} />)}</div> : <button type="button" onClick={() => setOpen(true)} className="mt-4 flex min-h-20 w-full items-center justify-center gap-2 rounded-xl border border-dashed text-sm text-muted-foreground"><UploadCloud className="h-5 w-5" />Adicionar o primeiro arquivo</button>}<FileCreateDialog open={open} onOpenChange={setOpen} clients={[client]} folders={defaultFolders} fixedClient={client} onUpload={files.upload.mutateAsync} onLink={files.addLink.mutateAsync} /></section>;
}

type CreateInput = { title?: string; category: string; folder: string; clientId?: string | null; clientName?: string | null; tags?: string[] };
function FileCreateDialog({ open, onOpenChange, clients, folders, fixedClient, onUpload, onLink }: { open: boolean; onOpenChange: (open: boolean) => void; clients: Client[]; folders: string[]; fixedClient?: Client; onUpload: (input: CreateInput & { file: File }) => Promise<unknown>; onLink: (input: CreateInput & { title: string; url: string }) => Promise<unknown> }) {
  const { toast } = useToast();
  const [mode, setMode] = useState<BrokerFileType>("image");
  const [pending, setPending] = useState(false);
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const selectedId = fixedClient?.id ?? (String(form.get("clientId") || "") || null); const selected = clients.find((client) => client.id === selectedId); const common = { title: String(form.get("title") ?? ""), category: String(form.get("category") || "Geral"), folder: String(form.get("folder") || (fixedClient ? fixedClient.name : "Geral")), clientId: selectedId, clientName: fixedClient?.name ?? selected?.name ?? null, tags: String(form.get("tags") ?? "").split(",").map((item) => item.trim()).filter(Boolean) }; setPending(true); try { if (mode === "link") await onLink({ ...common, title: common.title || "Link", url: String(form.get("url")) }); else { const file = form.get("file"); if (!(file instanceof File) || !file.size) throw new Error("Selecione um arquivo."); await onUpload({ ...common, file }); } toast({ title: "Arquivo adicionado e organizado." }); onOpenChange(false); } catch (error) { toast({ title: error instanceof Error ? error.message : "Não foi possível adicionar o arquivo.", variant: "error" }); } finally { setPending(false); } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Novo arquivo</DialogTitle><DialogDescription>Escolha a pasta e, se necessário, vincule o material a um cliente.</DialogDescription></DialogHeader><form onSubmit={submit} className="grid gap-4"><div className="grid grid-cols-3 gap-2"><ModeButton active={mode === "image"} icon={FileImage} label="Foto" onClick={() => setMode("image")} /><ModeButton active={mode === "pdf"} icon={FileText} label="PDF" onClick={() => setMode("pdf")} /><ModeButton active={mode === "link"} icon={Link2} label="Link" onClick={() => setMode("link")} /></div><div><Label htmlFor="file-title">Nome</Label><Input id="file-title" name="title" className="mt-2" placeholder={mode === "link" ? "Ex: Pasta de documentos" : "Opcional: usa o nome do arquivo"} /></div><div className="grid gap-3 sm:grid-cols-2"><div><Label htmlFor="file-folder">Pasta</Label><Input id="file-folder" name="folder" list="file-folders" defaultValue={fixedClient?.name ?? "Geral"} className="mt-2" /><datalist id="file-folders">{folders.map((item) => <option key={item} value={item} />)}</datalist></div><div><Label htmlFor="file-category">Categoria</Label><Input id="file-category" name="category" list="file-categories" defaultValue={fixedClient ? "Clientes" : "Geral"} className="mt-2" /><datalist id="file-categories">{categories.map((item) => <option key={item} value={item} />)}</datalist></div></div>{fixedClient ? <div><Label>Cliente</Label><div className="mt-2 flex h-12 items-center rounded-2xl border bg-muted/40 px-4 text-sm font-semibold">{fixedClient.name}</div></div> : <div><Label htmlFor="file-client">Cliente</Label><select id="file-client" name="clientId" className="mt-2 h-12 w-full rounded-2xl border bg-background px-4 text-sm"><option value="">Arquivo geral</option>{clients.map((client) => <option key={client.id} value={client.id}>{client.name}</option>)}</select></div>}{mode === "link" ? <div><Label htmlFor="file-url">Link</Label><Input id="file-url" name="url" type="url" className="mt-2" placeholder="https://..." required /></div> : <div><Label htmlFor="file-upload">{mode === "image" ? "Selecionar foto" : "Selecionar PDF"}</Label><Input id="file-upload" name="file" type="file" accept={mode === "image" ? "image/*" : "application/pdf"} className="mt-2 pt-3" required /></div>}<div><Label htmlFor="file-tags">Etiquetas</Label><Input id="file-tags" name="tags" className="mt-2" placeholder="contrato, compra, apartamento" /></div><Button disabled={pending}>{pending ? "Salvando..." : "Salvar arquivo"}</Button></form></DialogContent></Dialog>;
}

function FileItem({ file, view, compact, onFavorite, onRemove }: { file: BrokerFile; view: ViewMode; compact?: boolean; onFavorite: () => void; onRemove: () => void }) { const Icon = file.file_type === "image" ? FileImage : file.file_type === "pdf" ? FileText : Link2; const href = file.file_type === "link" ? file.external_url : file.file_url; if (view === "list") return <article className={cn("flex min-w-0 items-center gap-3 rounded-xl border bg-card", compact ? "p-2.5" : "p-3")}><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-muted text-primary"><Icon className="h-5 w-5" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{file.title}</p><p className="truncate text-[11px] text-muted-foreground">{file.folder || "Geral"} · {file.category}{file.client_name ? ` · ${file.client_name}` : ""}{file.file_size ? ` · ${formatBytes(file.file_size)}` : ""}</p></div><FileActions file={file} href={href} onFavorite={onFavorite} onRemove={onRemove} /></article>; return <article className="overflow-hidden rounded-2xl border bg-card shadow-sm"><div className="relative aspect-[16/8] bg-muted">{file.file_type === "image" && file.file_url ? <img src={file.file_url} alt="" className="h-full w-full object-cover" /> : <div className="grid h-full place-items-center"><Icon className="h-10 w-10 text-primary/55" /></div>}<span className="absolute left-3 top-3 rounded-full bg-black/70 px-2.5 py-1 text-[10px] font-semibold uppercase text-white">{file.folder || "Geral"}</span>{file.is_favorite && <Star className="absolute right-3 top-3 h-5 w-5 fill-amber-400 text-amber-400" />}</div><div className="p-4"><h2 className="truncate font-semibold">{file.title}</h2><p className="mt-1 truncate text-xs text-muted-foreground">{file.category}{file.client_name ? ` · ${file.client_name}` : ""}{file.file_size ? ` · ${formatBytes(file.file_size)}` : ""}</p><div className="mt-4 flex items-center justify-between"><span className="text-[10px] text-muted-foreground">{new Date(file.created_at).toLocaleDateString("pt-BR")}</span><FileActions file={file} href={href} onFavorite={onFavorite} onRemove={onRemove} /></div></div></article>; }
function FileActions({ file, href, onFavorite, onRemove }: { file: BrokerFile; href?: string | null; onFavorite: () => void; onRemove: () => void }) { const [confirming, setConfirming] = useState(false); return <div className="flex shrink-0 gap-1"><Button size="icon" variant="ghost" title={file.is_favorite ? "Remover dos favoritos" : "Favoritar"} onClick={onFavorite}><Star className={cn("h-4 w-4", file.is_favorite && "fill-amber-400 text-amber-500")} /></Button>{href && <Button size="icon" variant="outline" asChild title={file.file_type === "link" ? "Abrir link" : "Baixar arquivo"}><a href={href} target="_blank" rel="noreferrer">{file.file_type === "link" ? <ExternalLink className="h-4 w-4" /> : <Download className="h-4 w-4" />}</a></Button>}{confirming ? <><Button size="sm" variant="destructive" onClick={onRemove}>Excluir</Button><Button size="sm" variant="ghost" onClick={() => setConfirming(false)}>Voltar</Button></> : <Button size="icon" variant="ghost" title="Remover" onClick={() => setConfirming(true)}><Trash2 className="h-4 w-4" /></Button>}</div>; }
function Metric({ label, value, icon: Icon, active, onClick }: { label: string; value: number; icon: React.ElementType; active: boolean; onClick: () => void }) { return <button type="button" onClick={onClick} className={cn("rounded-2xl border bg-card p-4 text-left transition", active && "border-primary bg-primary/5 ring-1 ring-primary/20")}><div className="flex items-center justify-between"><p className="text-xs font-semibold text-muted-foreground">{label}</p><Icon className="h-4 w-4 text-primary" /></div><p className="mt-3 text-2xl font-semibold">{value}</p></button>; }
function Filter({ value, onChange, options }: { value: string; onChange: (value: string) => void; options: Array<[string,string]> }) { return <select value={value} onChange={(event) => onChange(event.target.value)} className="h-12 min-w-0 max-w-full rounded-2xl border bg-background px-3 text-sm">{options.map(([optionValue,label]) => <option key={optionValue} value={optionValue}>{label}</option>)}</select>; }
function ViewButton({ active, icon: Icon, label, onClick }: { active: boolean; icon: React.ElementType; label: string; onClick: () => void }) { return <button type="button" title={label} onClick={onClick} className={cn("grid place-items-center rounded-lg", active && "bg-card text-primary shadow-sm")}><Icon className="h-4 w-4" /></button>; }
function ModeButton({ active, icon: Icon, label, onClick }: { active: boolean; icon: React.ElementType; label: string; onClick: () => void }) { return <button type="button" onClick={onClick} className={cn("flex min-h-16 flex-col items-center justify-center gap-1 rounded-xl border text-xs font-semibold", active ? "border-primary bg-primary/10 text-primary" : "bg-card")}><Icon className="h-5 w-5" />{label}</button>; }
function EmptyFiles({ onAdd }: { onAdd: () => void }) { return <div className="rounded-2xl border border-dashed bg-card px-5 py-14 text-center"><FileArchive className="mx-auto h-9 w-9 text-muted-foreground" /><h2 className="mt-3 font-semibold">Nenhum arquivo encontrado</h2><p className="mt-1 text-sm text-muted-foreground">Ajuste os filtros ou adicione uma foto, PDF ou link.</p><Button className="mt-4" variant="outline" onClick={onAdd}><Plus className="h-4 w-4" />Adicionar arquivo</Button></div>; }
