import { Bell, CalendarClock, CheckCheck, CircleDollarSign, ListChecks, Newspaper, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { useNotifications, type AppNotification } from "./use-notifications";
import type { AppView } from "@/types/ui";

export function NotificationCenter({ open, onOpenChange, onNavigate }: { open: boolean; onOpenChange: (open: boolean) => void; onNavigate: (view: AppView) => void }) {
  const notifications = useNotifications();
  function openItem(item: AppNotification) { if (!item.read_at) void notifications.markRead.mutateAsync(item.id); if (item.target_view) onNavigate(item.target_view as AppView); onOpenChange(false); }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-lg"><DialogHeader><div className="flex items-center justify-between gap-3"><div><DialogTitle>Notificações</DialogTitle><DialogDescription>Lembretes da sua rotina e do financeiro.</DialogDescription></div>{notifications.unreadCount > 0 && <Button size="sm" variant="ghost" onClick={() => void notifications.markAllRead.mutateAsync()}><CheckCheck className="h-4 w-4" />Ler todas</Button>}</div></DialogHeader><div className="max-h-[65vh] space-y-2 overflow-y-auto pr-1">{notifications.notifications.length ? notifications.notifications.map((item) => { const Icon = notificationIcon(item.kind); return <button key={item.id} type="button" onClick={() => openItem(item)} className="flex w-full gap-3 rounded-2xl border bg-card p-3 text-left transition hover:border-primary/35"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary"><Icon className="h-4 w-4" /></span><span className="min-w-0 flex-1"><span className="flex items-center gap-2"><span className="truncate text-sm font-semibold">{item.title}</span>{!item.read_at && <span className="h-2 w-2 shrink-0 rounded-full bg-primary" />}</span><span className="mt-1 block text-xs leading-5 text-muted-foreground">{item.body}</span><span className="mt-1 block text-[10px] text-muted-foreground">{new Date(item.created_at).toLocaleString("pt-BR")}</span></span></button>; }) : <div className="grid min-h-48 place-items-center rounded-2xl border border-dashed text-center"><div><Bell className="mx-auto h-7 w-7 text-muted-foreground" /><p className="mt-3 text-sm font-semibold">Tudo em dia</p><p className="mt-1 text-xs text-muted-foreground">Novos lembretes aparecerão aqui.</p></div></div>}</div></DialogContent></Dialog>;
}

function notificationIcon(kind: AppNotification["kind"]) { return kind === "appointment" ? CalendarClock : kind === "task" ? ListChecks : kind === "finance" || kind === "commission" ? CircleDollarSign : kind === "follow_up" ? UserRound : kind === "market" ? Newspaper : Bell; }
